<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2012r2

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:tbf="http://www.altova.com/MapForce/UDF/tbf" xmlns:ns0="http://www.ilsp.gr/META-XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="tbf ns0 xs">
	<xsl:template name="tbf:tbf1_foreseenUseInfoType">
		<xsl:param name="input" select="/.."/>
		<xsl:for-each select="$input/node()">
			<xsl:if test="not(boolean(self::text()))">
				<xsl:if test="not(boolean(self::*))">
					<xsl:value-of select="."/>
				</xsl:if>
			</xsl:if>
			<xsl:if test="string(boolean(self::ns0:foreseenUse)) != 'false'">
				<xsl:element name="{name(.)}" namespace="{namespace-uri(.)}">
					<xsl:value-of select="string(.)"/>
				</xsl:element>
			</xsl:if>
			<xsl:if test="string(boolean(self::ns0:useNLPSpecific)) != 'false'">
				<xsl:element name="{name(.)}" namespace="{namespace-uri(.)}">
					<xsl:value-of select="string(.)"/>
				</xsl:element>
			</xsl:if>
		</xsl:for-each>
	</xsl:template>
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<resourceInfo xmlns="http://www.ilsp.gr/META-XMLSchema">
			<xsl:attribute name="xsi:schemaLocation" namespace="http://www.w3.org/2001/XMLSchema-instance">http://www.ilsp.gr/META-XMLSchema C:/develop/metashare/transform/schemaTransform/v2.0/META-SHARE-Resource.xsd</xsl:attribute>
			<xsl:for-each select="ns0:Resource">
				<identificationInfo>
					<resourceName>
						<xsl:variable name="var1_lang">
							<xsl:if test="ns0:IdentificationInfo/ns0:resourceName/@ns0:lang">
								<xsl:value-of select="'1'"/>
							</xsl:if>
						</xsl:variable>
						<xsl:if test="string(boolean(string($var1_lang))) != 'false'">
							<xsl:attribute name="lang" namespace="">
								<xsl:value-of select="string(ns0:IdentificationInfo/ns0:resourceName/@ns0:lang)"/>
							</xsl:attribute>
						</xsl:if>
						<xsl:value-of select="string(ns0:IdentificationInfo/ns0:resourceName)"/>
					</resourceName>
					<xsl:for-each select="ns0:IdentificationInfo/ns0:resourceShortName">
						<resourceShortName>
							<xsl:variable name="var2_lang">
								<xsl:if test="@ns0:lang">
									<xsl:value-of select="'1'"/>
								</xsl:if>
							</xsl:variable>
							<xsl:if test="string(boolean(string($var2_lang))) != 'false'">
								<xsl:attribute name="lang" namespace="">
									<xsl:value-of select="string(@ns0:lang)"/>
								</xsl:attribute>
							</xsl:if>
							<xsl:value-of select="string(.)"/>
						</resourceShortName>
					</xsl:for-each>
					<xsl:for-each select="ns0:IdentificationInfo/ns0:url">
						<url>
							<xsl:value-of select="string(.)"/>
						</url>
					</xsl:for-each>
					<metaShareId>n/a</metaShareId>
					<identifier>
						<xsl:value-of select="string(ns0:IdentificationInfo/ns0:pid)"/>
					</identifier>
				</identificationInfo>
				<distributionInfo>
					<availability>
						<xsl:value-of select="string(ns0:DistributionInfo/ns0:availability)"/>
					</availability>
					<xsl:for-each select="ns0:DistributionInfo/ns0:iprHolder">
						<iprHolder>
							<xsl:for-each select="ns0:PersonInfo">
								<personInfo>
									<xsl:for-each select="ns0:surname">
										<surname>
											<xsl:variable name="var3_lang">
												<xsl:if test="@ns0:lang">
													<xsl:value-of select="'1'"/>
												</xsl:if>
											</xsl:variable>
											<xsl:if test="string(boolean(string($var3_lang))) != 'false'">
												<xsl:attribute name="lang" namespace="">
													<xsl:value-of select="string(@ns0:lang)"/>
												</xsl:attribute>
											</xsl:if>
											<xsl:value-of select="string(.)"/>
										</surname>
									</xsl:for-each>
									<xsl:for-each select="ns0:givenName">
										<givenName>
											<xsl:variable name="var4_lang">
												<xsl:if test="@ns0:lang">
													<xsl:value-of select="'1'"/>
												</xsl:if>
											</xsl:variable>
											<xsl:if test="string(boolean(string($var4_lang))) != 'false'">
												<xsl:attribute name="lang" namespace="">
													<xsl:value-of select="string(@ns0:lang)"/>
												</xsl:attribute>
											</xsl:if>
											<xsl:value-of select="string(.)"/>
										</givenName>
									</xsl:for-each>
									<communicationInfo>
										<xsl:for-each select="ns0:CommunicationInfo/ns0:email">
											<email>
												<xsl:value-of select="string(.)"/>
											</email>
										</xsl:for-each>
										<xsl:for-each select="ns0:CommunicationInfo/ns0:url">
											<url>
												<xsl:value-of select="string(.)"/>
											</url>
										</xsl:for-each>
										<xsl:for-each select="ns0:CommunicationInfo/ns0:address">
											<address>
												<xsl:value-of select="string(.)"/>
											</address>
										</xsl:for-each>
										<xsl:for-each select="ns0:CommunicationInfo/ns0:zipCode">
											<zipCode>
												<xsl:value-of select="string(.)"/>
											</zipCode>
										</xsl:for-each>
										<xsl:for-each select="ns0:CommunicationInfo/ns0:city">
											<city>
												<xsl:value-of select="string(.)"/>
											</city>
										</xsl:for-each>
										<xsl:for-each select="ns0:CommunicationInfo/ns0:country">
											<country>
												<xsl:value-of select="string(.)"/>
											</country>
										</xsl:for-each>
										<xsl:for-each select="ns0:CommunicationInfo/ns0:telephoneNumber">
											<telephoneNumber>
												<xsl:value-of select="string(.)"/>
											</telephoneNumber>
										</xsl:for-each>
										<xsl:for-each select="ns0:CommunicationInfo/ns0:faxNumber">
											<faxNumber>
												<xsl:value-of select="string(.)"/>
											</faxNumber>
										</xsl:for-each>
									</communicationInfo>
									<xsl:for-each select="ns0:position">
										<position>
											<xsl:value-of select="string(.)"/>
										</position>
									</xsl:for-each>
									<xsl:for-each select="ns0:affiliation">
										<affiliation>
											<xsl:value-of select="/.."/>
										</affiliation>
									</xsl:for-each>
								</personInfo>
							</xsl:for-each>
							<xsl:for-each select="ns0:OrganizationInfo">
								<organizationInfo>
									<organizationName>
										<xsl:variable name="var5_lang">
											<xsl:if test="ns0:organizationName/@ns0:lang">
												<xsl:value-of select="'1'"/>
											</xsl:if>
										</xsl:variable>
										<xsl:if test="string(boolean(string($var5_lang))) != 'false'">
											<xsl:attribute name="lang" namespace="">
												<xsl:value-of select="string(ns0:organizationName/@ns0:lang)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:value-of select="string(ns0:organizationName)"/>
									</organizationName>
									<xsl:for-each select="ns0:organizationShortName">
										<organizationShortName>
											<xsl:variable name="var6_lang">
												<xsl:if test="@ns0:lang">
													<xsl:value-of select="'1'"/>
												</xsl:if>
											</xsl:variable>
											<xsl:if test="string(boolean(string($var6_lang))) != 'false'">
												<xsl:attribute name="lang" namespace="">
													<xsl:value-of select="string(@ns0:lang)"/>
												</xsl:attribute>
											</xsl:if>
											<xsl:value-of select="string(.)"/>
										</organizationShortName>
									</xsl:for-each>
									<xsl:for-each select="ns0:departmentName">
										<departmentName>
											<xsl:variable name="var7_lang">
												<xsl:if test="@ns0:lang">
													<xsl:value-of select="'1'"/>
												</xsl:if>
											</xsl:variable>
											<xsl:if test="string(boolean(string($var7_lang))) != 'false'">
												<xsl:attribute name="lang" namespace="">
													<xsl:value-of select="string(@ns0:lang)"/>
												</xsl:attribute>
											</xsl:if>
											<xsl:value-of select="string(.)"/>
										</departmentName>
									</xsl:for-each>
									<communicationInfo>
										<xsl:for-each select="ns0:CommunicationInfo/ns0:email">
											<email>
												<xsl:value-of select="string(.)"/>
											</email>
										</xsl:for-each>
										<xsl:for-each select="ns0:CommunicationInfo/ns0:url">
											<url>
												<xsl:value-of select="string(.)"/>
											</url>
										</xsl:for-each>
										<xsl:for-each select="ns0:CommunicationInfo/ns0:address">
											<address>
												<xsl:value-of select="string(.)"/>
											</address>
										</xsl:for-each>
										<xsl:for-each select="ns0:CommunicationInfo/ns0:zipCode">
											<zipCode>
												<xsl:value-of select="string(.)"/>
											</zipCode>
										</xsl:for-each>
										<xsl:for-each select="ns0:CommunicationInfo/ns0:city">
											<city>
												<xsl:value-of select="string(.)"/>
											</city>
										</xsl:for-each>
										<xsl:for-each select="ns0:CommunicationInfo/ns0:country">
											<country>
												<xsl:value-of select="string(.)"/>
											</country>
										</xsl:for-each>
										<xsl:for-each select="ns0:CommunicationInfo/ns0:telephoneNumber">
											<telephoneNumber>
												<xsl:value-of select="string(.)"/>
											</telephoneNumber>
										</xsl:for-each>
										<xsl:for-each select="ns0:CommunicationInfo/ns0:faxNumber">
											<faxNumber>
												<xsl:value-of select="string(.)"/>
											</faxNumber>
										</xsl:for-each>
									</communicationInfo>
								</organizationInfo>
							</xsl:for-each>
						</iprHolder>
					</xsl:for-each>
				</distributionInfo>
				<xsl:for-each select="ns0:contactPerson">
					<contactPerson>
						<xsl:for-each select="ns0:surname">
							<surname>
								<xsl:variable name="var8_lang">
									<xsl:if test="@ns0:lang">
										<xsl:value-of select="'1'"/>
									</xsl:if>
								</xsl:variable>
								<xsl:if test="string(boolean(string($var8_lang))) != 'false'">
									<xsl:attribute name="lang" namespace="">
										<xsl:value-of select="string(@ns0:lang)"/>
									</xsl:attribute>
								</xsl:if>
								<xsl:value-of select="string(.)"/>
							</surname>
						</xsl:for-each>
						<xsl:for-each select="ns0:givenName">
							<givenName>
								<xsl:variable name="var9_lang">
									<xsl:if test="@ns0:lang">
										<xsl:value-of select="'1'"/>
									</xsl:if>
								</xsl:variable>
								<xsl:if test="string(boolean(string($var9_lang))) != 'false'">
									<xsl:attribute name="lang" namespace="">
										<xsl:value-of select="string(@ns0:lang)"/>
									</xsl:attribute>
								</xsl:if>
								<xsl:value-of select="string(.)"/>
							</givenName>
						</xsl:for-each>
						<communicationInfo>
							<xsl:for-each select="ns0:CommunicationInfo/ns0:email">
								<email>
									<xsl:value-of select="string(.)"/>
								</email>
							</xsl:for-each>
							<xsl:for-each select="ns0:CommunicationInfo/ns0:url">
								<url>
									<xsl:value-of select="string(.)"/>
								</url>
							</xsl:for-each>
							<xsl:for-each select="ns0:CommunicationInfo/ns0:address">
								<address>
									<xsl:value-of select="string(.)"/>
								</address>
							</xsl:for-each>
							<xsl:for-each select="ns0:CommunicationInfo/ns0:zipCode">
								<zipCode>
									<xsl:value-of select="string(.)"/>
								</zipCode>
							</xsl:for-each>
							<xsl:for-each select="ns0:CommunicationInfo/ns0:city">
								<city>
									<xsl:value-of select="string(.)"/>
								</city>
							</xsl:for-each>
							<xsl:for-each select="ns0:CommunicationInfo/ns0:country">
								<country>
									<xsl:value-of select="string(.)"/>
								</country>
							</xsl:for-each>
							<xsl:for-each select="ns0:CommunicationInfo/ns0:telephoneNumber">
								<telephoneNumber>
									<xsl:value-of select="string(.)"/>
								</telephoneNumber>
							</xsl:for-each>
							<xsl:for-each select="ns0:CommunicationInfo/ns0:faxNumber">
								<faxNumber>
									<xsl:value-of select="string(.)"/>
								</faxNumber>
							</xsl:for-each>
						</communicationInfo>
						<xsl:for-each select="ns0:position">
							<position>
								<xsl:value-of select="string(.)"/>
							</position>
						</xsl:for-each>
						<xsl:for-each select="ns0:affiliation">
							<affiliation>
								<organizationName>
									<xsl:variable name="var10_lang">
										<xsl:if test="ns0:OrganizationInfo/ns0:organizationName/@ns0:lang">
											<xsl:value-of select="'1'"/>
										</xsl:if>
									</xsl:variable>
									<xsl:if test="string(boolean(string($var10_lang))) != 'false'">
										<xsl:attribute name="lang" namespace="">
											<xsl:value-of select="string(ns0:OrganizationInfo/ns0:organizationName/@ns0:lang)"/>
										</xsl:attribute>
									</xsl:if>
									<xsl:value-of select="string(ns0:OrganizationInfo/ns0:organizationName)"/>
								</organizationName>
								<xsl:for-each select="ns0:OrganizationInfo/ns0:organizationShortName">
									<organizationShortName>
										<xsl:variable name="var11_lang">
											<xsl:if test="@ns0:lang">
												<xsl:value-of select="'1'"/>
											</xsl:if>
										</xsl:variable>
										<xsl:if test="string(boolean(string($var11_lang))) != 'false'">
											<xsl:attribute name="lang" namespace="">
												<xsl:value-of select="string(@ns0:lang)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:value-of select="string(.)"/>
									</organizationShortName>
								</xsl:for-each>
								<xsl:for-each select="ns0:OrganizationInfo/ns0:departmentName">
									<departmentName>
										<xsl:variable name="var12_lang">
											<xsl:if test="@ns0:lang">
												<xsl:value-of select="'1'"/>
											</xsl:if>
										</xsl:variable>
										<xsl:if test="string(boolean(string($var12_lang))) != 'false'">
											<xsl:attribute name="lang" namespace="">
												<xsl:value-of select="string(@ns0:lang)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:value-of select="string(.)"/>
									</departmentName>
								</xsl:for-each>
								<communicationInfo>
									<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:email">
										<email>
											<xsl:value-of select="string(.)"/>
										</email>
									</xsl:for-each>
									<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:url">
										<url>
											<xsl:value-of select="string(.)"/>
										</url>
									</xsl:for-each>
									<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:address">
										<address>
											<xsl:value-of select="string(.)"/>
										</address>
									</xsl:for-each>
									<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:zipCode">
										<zipCode>
											<xsl:value-of select="string(.)"/>
										</zipCode>
									</xsl:for-each>
									<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:city">
										<city>
											<xsl:value-of select="string(.)"/>
										</city>
									</xsl:for-each>
									<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:country">
										<country>
											<xsl:value-of select="string(.)"/>
										</country>
									</xsl:for-each>
									<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:telephoneNumber">
										<telephoneNumber>
											<xsl:value-of select="string(.)"/>
										</telephoneNumber>
									</xsl:for-each>
									<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:faxNumber">
										<faxNumber>
											<xsl:value-of select="string(.)"/>
										</faxNumber>
									</xsl:for-each>
								</communicationInfo>
							</affiliation>
						</xsl:for-each>
					</contactPerson>
				</xsl:for-each>
				<metadataInfo>
					<metadataCreationDate>
						<xsl:value-of select="string(ns0:MetadataInfo/ns0:metadataCreationDate)"/>
					</metadataCreationDate>
					<xsl:for-each select="ns0:MetadataInfo/ns0:metadataCreator">
						<metadataCreator>
							<xsl:for-each select="ns0:surname">
								<surname>
									<xsl:variable name="var13_lang">
										<xsl:if test="@ns0:lang">
											<xsl:value-of select="'1'"/>
										</xsl:if>
									</xsl:variable>
									<xsl:if test="string(boolean(string($var13_lang))) != 'false'">
										<xsl:attribute name="lang" namespace="">
											<xsl:value-of select="string(@ns0:lang)"/>
										</xsl:attribute>
									</xsl:if>
									<xsl:value-of select="string(.)"/>
								</surname>
							</xsl:for-each>
							<xsl:for-each select="ns0:givenName">
								<givenName>
									<xsl:variable name="var14_lang">
										<xsl:if test="@ns0:lang">
											<xsl:value-of select="'1'"/>
										</xsl:if>
									</xsl:variable>
									<xsl:if test="string(boolean(string($var14_lang))) != 'false'">
										<xsl:attribute name="lang" namespace="">
											<xsl:value-of select="string(@ns0:lang)"/>
										</xsl:attribute>
									</xsl:if>
									<xsl:value-of select="string(.)"/>
								</givenName>
							</xsl:for-each>
							<communicationInfo>
								<xsl:for-each select="ns0:CommunicationInfo/ns0:email">
									<email>
										<xsl:value-of select="string(.)"/>
									</email>
								</xsl:for-each>
								<xsl:for-each select="ns0:CommunicationInfo/ns0:url">
									<url>
										<xsl:value-of select="string(.)"/>
									</url>
								</xsl:for-each>
								<xsl:for-each select="ns0:CommunicationInfo/ns0:address">
									<address>
										<xsl:value-of select="string(.)"/>
									</address>
								</xsl:for-each>
								<xsl:for-each select="ns0:CommunicationInfo/ns0:zipCode">
									<zipCode>
										<xsl:value-of select="string(.)"/>
									</zipCode>
								</xsl:for-each>
								<xsl:for-each select="ns0:CommunicationInfo/ns0:city">
									<city>
										<xsl:value-of select="string(.)"/>
									</city>
								</xsl:for-each>
								<xsl:for-each select="ns0:CommunicationInfo/ns0:country">
									<country>
										<xsl:value-of select="string(.)"/>
									</country>
								</xsl:for-each>
								<xsl:for-each select="ns0:CommunicationInfo/ns0:telephoneNumber">
									<telephoneNumber>
										<xsl:value-of select="string(.)"/>
									</telephoneNumber>
								</xsl:for-each>
								<xsl:for-each select="ns0:CommunicationInfo/ns0:faxNumber">
									<faxNumber>
										<xsl:value-of select="string(.)"/>
									</faxNumber>
								</xsl:for-each>
							</communicationInfo>
							<xsl:for-each select="ns0:position">
								<position>
									<xsl:value-of select="string(.)"/>
								</position>
							</xsl:for-each>
							<xsl:for-each select="ns0:affiliation">
								<affiliation>
									<organizationName>
										<xsl:variable name="var15_lang">
											<xsl:if test="ns0:OrganizationInfo/ns0:organizationName/@ns0:lang">
												<xsl:value-of select="'1'"/>
											</xsl:if>
										</xsl:variable>
										<xsl:if test="string(boolean(string($var15_lang))) != 'false'">
											<xsl:attribute name="lang" namespace="">
												<xsl:value-of select="string(ns0:OrganizationInfo/ns0:organizationName/@ns0:lang)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:value-of select="string(ns0:OrganizationInfo/ns0:organizationName)"/>
									</organizationName>
									<xsl:for-each select="ns0:OrganizationInfo/ns0:organizationShortName">
										<organizationShortName>
											<xsl:variable name="var16_lang">
												<xsl:if test="@ns0:lang">
													<xsl:value-of select="'1'"/>
												</xsl:if>
											</xsl:variable>
											<xsl:if test="string(boolean(string($var16_lang))) != 'false'">
												<xsl:attribute name="lang" namespace="">
													<xsl:value-of select="string(@ns0:lang)"/>
												</xsl:attribute>
											</xsl:if>
											<xsl:value-of select="string(.)"/>
										</organizationShortName>
									</xsl:for-each>
									<xsl:for-each select="ns0:OrganizationInfo/ns0:departmentName">
										<departmentName>
											<xsl:variable name="var17_lang">
												<xsl:if test="@ns0:lang">
													<xsl:value-of select="'1'"/>
												</xsl:if>
											</xsl:variable>
											<xsl:if test="string(boolean(string($var17_lang))) != 'false'">
												<xsl:attribute name="lang" namespace="">
													<xsl:value-of select="string(@ns0:lang)"/>
												</xsl:attribute>
											</xsl:if>
											<xsl:value-of select="string(.)"/>
										</departmentName>
									</xsl:for-each>
									<communicationInfo>
										<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:email">
											<email>
												<xsl:value-of select="string(.)"/>
											</email>
										</xsl:for-each>
										<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:url">
											<url>
												<xsl:value-of select="string(.)"/>
											</url>
										</xsl:for-each>
										<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:address">
											<address>
												<xsl:value-of select="string(.)"/>
											</address>
										</xsl:for-each>
										<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:zipCode">
											<zipCode>
												<xsl:value-of select="string(.)"/>
											</zipCode>
										</xsl:for-each>
										<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:city">
											<city>
												<xsl:value-of select="string(.)"/>
											</city>
										</xsl:for-each>
										<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:country">
											<country>
												<xsl:value-of select="string(.)"/>
											</country>
										</xsl:for-each>
										<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:telephoneNumber">
											<telephoneNumber>
												<xsl:value-of select="string(.)"/>
											</telephoneNumber>
										</xsl:for-each>
										<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:faxNumber">
											<faxNumber>
												<xsl:value-of select="string(.)"/>
											</faxNumber>
										</xsl:for-each>
									</communicationInfo>
								</affiliation>
							</xsl:for-each>
						</metadataCreator>
					</xsl:for-each>
					<xsl:for-each select="ns0:MetadataInfo/ns0:source">
						<source>
							<xsl:value-of select="string(.)"/>
						</source>
					</xsl:for-each>
					<xsl:for-each select="ns0:MetadataInfo/ns0:originalMetadataSchema">
						<originalMetadataSchema>
							<xsl:value-of select="string(.)"/>
						</originalMetadataSchema>
					</xsl:for-each>
					<xsl:for-each select="ns0:MetadataInfo/ns0:originalMetadataLink">
						<originalMetadataLink>
							<xsl:value-of select="string(.)"/>
						</originalMetadataLink>
					</xsl:for-each>
					<xsl:for-each select="ns0:MetadataInfo/ns0:metadataLastDateUpdated">
						<metadataLastDateUpdated>
							<xsl:value-of select="string(.)"/>
						</metadataLastDateUpdated>
					</xsl:for-each>
					<xsl:for-each select="ns0:MetadataInfo/ns0:revision">
						<revision>
							<xsl:value-of select="string(.)"/>
						</revision>
					</xsl:for-each>
				</metadataInfo>
				<xsl:for-each select="ns0:VersionInfo">
					<versionInfo>
						<version>
							<xsl:value-of select="string(ns0:version)"/>
						</version>
						<xsl:for-each select="ns0:revision">
							<revision>
								<xsl:value-of select="string(.)"/>
							</revision>
						</xsl:for-each>
						<xsl:for-each select="ns0:lastDateUpdated">
							<lastDateUpdated>
								<xsl:value-of select="string(.)"/>
							</lastDateUpdated>
						</xsl:for-each>
						<xsl:for-each select="ns0:updateFrequency">
							<updateFrequency>
								<xsl:value-of select="string(.)"/>
							</updateFrequency>
						</xsl:for-each>
					</versionInfo>
				</xsl:for-each>
				<xsl:for-each select="ns0:ValidationInfo">
					<validationInfo>
						<validated>
							<xsl:value-of select="string((translate(string(ns0:validated), '1falseru0 ', 't') = 't'))"/>
						</validated>
						<xsl:for-each select="ns0:validationType">
							<validationType>
								<xsl:value-of select="string(.)"/>
							</validationType>
						</xsl:for-each>
						<xsl:for-each select="ns0:validationMode">
							<validationMode>
								<xsl:value-of select="string(.)"/>
							</validationMode>
						</xsl:for-each>
						<xsl:for-each select="ns0:validationModeDetails">
							<validationModeDetails>
								<xsl:value-of select="string(.)"/>
							</validationModeDetails>
						</xsl:for-each>
						<xsl:for-each select="ns0:validationExtent">
							<validationExtent>
								<xsl:value-of select="string(.)"/>
							</validationExtent>
						</xsl:for-each>
						<xsl:for-each select="ns0:validationExtentDetails">
							<validationExtentDetails>
								<xsl:value-of select="string(.)"/>
							</validationExtentDetails>
						</xsl:for-each>
						<xsl:for-each select="ns0:sizePerValidation">
							<sizePerValidation>
								<size>
									<xsl:value-of select="string(ns0:size)"/>
								</size>
								<sizeUnit>
									<xsl:value-of select="string(ns0:sizeUnit)"/>
								</sizeUnit>
							</sizePerValidation>
						</xsl:for-each>
						<xsl:for-each select="ns0:validationReport">
							<validationReport>
								<documentUnstructured>
									<xsl:value-of select="string(.)"/>
								</documentUnstructured>
							</validationReport>
						</xsl:for-each>
						<xsl:for-each select="ns0:validationTool">
							<validationTool>
								<xsl:value-of select="/.."/>
							</validationTool>
						</xsl:for-each>
						<xsl:for-each select="ns0:validator">
							<validator>
								<xsl:for-each select="ns0:PersonInfo">
									<personInfo>
										<xsl:for-each select="ns0:surname">
											<surname>
												<xsl:variable name="var18_lang">
													<xsl:if test="@ns0:lang">
														<xsl:value-of select="'1'"/>
													</xsl:if>
												</xsl:variable>
												<xsl:if test="string(boolean(string($var18_lang))) != 'false'">
													<xsl:attribute name="lang" namespace="">
														<xsl:value-of select="string(@ns0:lang)"/>
													</xsl:attribute>
												</xsl:if>
												<xsl:value-of select="string(.)"/>
											</surname>
										</xsl:for-each>
										<xsl:for-each select="ns0:givenName">
											<givenName>
												<xsl:variable name="var19_lang">
													<xsl:if test="@ns0:lang">
														<xsl:value-of select="'1'"/>
													</xsl:if>
												</xsl:variable>
												<xsl:if test="string(boolean(string($var19_lang))) != 'false'">
													<xsl:attribute name="lang" namespace="">
														<xsl:value-of select="string(@ns0:lang)"/>
													</xsl:attribute>
												</xsl:if>
												<xsl:value-of select="string(.)"/>
											</givenName>
										</xsl:for-each>
										<xsl:for-each select="ns0:position">
											<position>
												<xsl:value-of select="string(.)"/>
											</position>
										</xsl:for-each>
										<xsl:for-each select="ns0:affiliation">
											<affiliation>
												<xsl:value-of select="/.."/>
											</affiliation>
										</xsl:for-each>
									</personInfo>
								</xsl:for-each>
								<xsl:for-each select="ns0:OrganizationInfo">
									<organizationInfo>
										<organizationName>
											<xsl:variable name="var20_lang">
												<xsl:if test="ns0:organizationName/@ns0:lang">
													<xsl:value-of select="'1'"/>
												</xsl:if>
											</xsl:variable>
											<xsl:if test="string(boolean(string($var20_lang))) != 'false'">
												<xsl:attribute name="lang" namespace="">
													<xsl:value-of select="string(ns0:organizationName/@ns0:lang)"/>
												</xsl:attribute>
											</xsl:if>
											<xsl:value-of select="string(ns0:organizationName)"/>
										</organizationName>
										<xsl:for-each select="ns0:organizationShortName">
											<organizationShortName>
												<xsl:variable name="var21_lang">
													<xsl:if test="@ns0:lang">
														<xsl:value-of select="'1'"/>
													</xsl:if>
												</xsl:variable>
												<xsl:if test="string(boolean(string($var21_lang))) != 'false'">
													<xsl:attribute name="lang" namespace="">
														<xsl:value-of select="string(@ns0:lang)"/>
													</xsl:attribute>
												</xsl:if>
												<xsl:value-of select="string(.)"/>
											</organizationShortName>
										</xsl:for-each>
										<xsl:for-each select="ns0:departmentName">
											<departmentName>
												<xsl:variable name="var22_lang">
													<xsl:if test="@ns0:lang">
														<xsl:value-of select="'1'"/>
													</xsl:if>
												</xsl:variable>
												<xsl:if test="string(boolean(string($var22_lang))) != 'false'">
													<xsl:attribute name="lang" namespace="">
														<xsl:value-of select="string(@ns0:lang)"/>
													</xsl:attribute>
												</xsl:if>
												<xsl:value-of select="string(.)"/>
											</departmentName>
										</xsl:for-each>
									</organizationInfo>
								</xsl:for-each>
							</validator>
						</xsl:for-each>
					</validationInfo>
				</xsl:for-each>
				<xsl:for-each select="ns0:UsageInfo">
					<usageInfo>
						<xsl:for-each select="ns0:accessTool">
							<accessTool>
								<xsl:value-of select="/.."/>
							</accessTool>
						</xsl:for-each>
						<xsl:for-each select="ns0:ForeseenUseInfo">
							<foreseenUseInfo>
								<xsl:call-template name="tbf:tbf1_foreseenUseInfoType">
									<xsl:with-param name="input" select="."/>
								</xsl:call-template>
							</foreseenUseInfo>
						</xsl:for-each>
						<xsl:for-each select="ns0:ActualUseInfo">
							<actualUseInfo>
								<actualUse>
									<xsl:value-of select="string(ns0:actualUse)"/>
								</actualUse>
								<xsl:for-each select="ns0:useNLPSpecific">
									<useNLPSpecific>
										<xsl:value-of select="string(.)"/>
									</useNLPSpecific>
								</xsl:for-each>
								<xsl:for-each select="ns0:usageProject">
									<usageProject>
										<projectName>
											<xsl:variable name="var23_lang">
												<xsl:if test="ns0:projectName/@ns0:lang">
													<xsl:value-of select="'1'"/>
												</xsl:if>
											</xsl:variable>
											<xsl:if test="string(boolean(string($var23_lang))) != 'false'">
												<xsl:attribute name="lang" namespace="">
													<xsl:value-of select="string(ns0:projectName/@ns0:lang)"/>
												</xsl:attribute>
											</xsl:if>
											<xsl:value-of select="string(ns0:projectName)"/>
										</projectName>
										<xsl:for-each select="ns0:projectShortName">
											<projectShortName>
												<xsl:variable name="var24_lang">
													<xsl:if test="@ns0:lang">
														<xsl:value-of select="'1'"/>
													</xsl:if>
												</xsl:variable>
												<xsl:if test="string(boolean(string($var24_lang))) != 'false'">
													<xsl:attribute name="lang" namespace="">
														<xsl:value-of select="string(@ns0:lang)"/>
													</xsl:attribute>
												</xsl:if>
												<xsl:value-of select="string(.)"/>
											</projectShortName>
										</xsl:for-each>
										<xsl:for-each select="ns0:projectID">
											<projectID>
												<xsl:value-of select="string(.)"/>
											</projectID>
										</xsl:for-each>
										<xsl:for-each select="ns0:url">
											<url>
												<xsl:value-of select="string(.)"/>
											</url>
										</xsl:for-each>
										<xsl:for-each select="ns0:fundingType">
											<fundingType>
												<xsl:value-of select="string(.)"/>
											</fundingType>
										</xsl:for-each>
										<xsl:for-each select="ns0:funder">
											<funder>
												<xsl:value-of select="string(.)"/>
											</funder>
										</xsl:for-each>
										<xsl:for-each select="ns0:fundingCountry">
											<fundingCountry>
												<xsl:value-of select="string(.)"/>
											</fundingCountry>
										</xsl:for-each>
										<xsl:for-each select="ns0:projectStartDate">
											<projectStartDate>
												<xsl:value-of select="string(.)"/>
											</projectStartDate>
										</xsl:for-each>
										<xsl:for-each select="ns0:projectEndDate">
											<projectEndDate>
												<xsl:value-of select="string(.)"/>
											</projectEndDate>
										</xsl:for-each>
									</usageProject>
								</xsl:for-each>
								<xsl:for-each select="ns0:actualUseDetails">
									<actualUseDetails>
										<xsl:value-of select="string(.)"/>
									</actualUseDetails>
								</xsl:for-each>
							</actualUseInfo>
						</xsl:for-each>
					</usageInfo>
				</xsl:for-each>
				<xsl:for-each select="ns0:ResourceCreationInfo">
					<resourceCreationInfo>
						<xsl:for-each select="ns0:resourceCreator">
							<resourceCreator>
								<xsl:for-each select="ns0:PersonInfo">
									<personInfo>
										<xsl:for-each select="ns0:surname">
											<surname>
												<xsl:variable name="var25_lang">
													<xsl:if test="@ns0:lang">
														<xsl:value-of select="'1'"/>
													</xsl:if>
												</xsl:variable>
												<xsl:if test="string(boolean(string($var25_lang))) != 'false'">
													<xsl:attribute name="lang" namespace="">
														<xsl:value-of select="string(@ns0:lang)"/>
													</xsl:attribute>
												</xsl:if>
												<xsl:value-of select="string(.)"/>
											</surname>
										</xsl:for-each>
										<xsl:for-each select="ns0:givenName">
											<givenName>
												<xsl:variable name="var26_lang">
													<xsl:if test="@ns0:lang">
														<xsl:value-of select="'1'"/>
													</xsl:if>
												</xsl:variable>
												<xsl:if test="string(boolean(string($var26_lang))) != 'false'">
													<xsl:attribute name="lang" namespace="">
														<xsl:value-of select="string(@ns0:lang)"/>
													</xsl:attribute>
												</xsl:if>
												<xsl:value-of select="string(.)"/>
											</givenName>
										</xsl:for-each>
										<communicationInfo>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:email">
												<email>
													<xsl:value-of select="string(.)"/>
												</email>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:url">
												<url>
													<xsl:value-of select="string(.)"/>
												</url>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:address">
												<address>
													<xsl:value-of select="string(.)"/>
												</address>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:zipCode">
												<zipCode>
													<xsl:value-of select="string(.)"/>
												</zipCode>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:city">
												<city>
													<xsl:value-of select="string(.)"/>
												</city>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:country">
												<country>
													<xsl:value-of select="string(.)"/>
												</country>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:telephoneNumber">
												<telephoneNumber>
													<xsl:value-of select="string(.)"/>
												</telephoneNumber>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:faxNumber">
												<faxNumber>
													<xsl:value-of select="string(.)"/>
												</faxNumber>
											</xsl:for-each>
										</communicationInfo>
										<xsl:for-each select="ns0:position">
											<position>
												<xsl:value-of select="string(.)"/>
											</position>
										</xsl:for-each>
										<xsl:for-each select="ns0:affiliation">
											<affiliation>
												<organizationName>
													<xsl:variable name="var27_lang">
														<xsl:if test="ns0:OrganizationInfo/ns0:organizationName/@ns0:lang">
															<xsl:value-of select="'1'"/>
														</xsl:if>
													</xsl:variable>
													<xsl:if test="string(boolean(string($var27_lang))) != 'false'">
														<xsl:attribute name="lang" namespace="">
															<xsl:value-of select="string(ns0:OrganizationInfo/ns0:organizationName/@ns0:lang)"/>
														</xsl:attribute>
													</xsl:if>
													<xsl:value-of select="string(ns0:OrganizationInfo/ns0:organizationName)"/>
												</organizationName>
												<xsl:for-each select="ns0:OrganizationInfo/ns0:organizationShortName">
													<organizationShortName>
														<xsl:variable name="var28_lang">
															<xsl:if test="@ns0:lang">
																<xsl:value-of select="'1'"/>
															</xsl:if>
														</xsl:variable>
														<xsl:if test="string(boolean(string($var28_lang))) != 'false'">
															<xsl:attribute name="lang" namespace="">
																<xsl:value-of select="string(@ns0:lang)"/>
															</xsl:attribute>
														</xsl:if>
														<xsl:value-of select="string(.)"/>
													</organizationShortName>
												</xsl:for-each>
												<xsl:for-each select="ns0:OrganizationInfo/ns0:departmentName">
													<departmentName>
														<xsl:variable name="var29_lang">
															<xsl:if test="@ns0:lang">
																<xsl:value-of select="'1'"/>
															</xsl:if>
														</xsl:variable>
														<xsl:if test="string(boolean(string($var29_lang))) != 'false'">
															<xsl:attribute name="lang" namespace="">
																<xsl:value-of select="string(@ns0:lang)"/>
															</xsl:attribute>
														</xsl:if>
														<xsl:value-of select="string(.)"/>
													</departmentName>
												</xsl:for-each>
												<communicationInfo>
													<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:email">
														<email>
															<xsl:value-of select="string(.)"/>
														</email>
													</xsl:for-each>
													<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:url">
														<url>
															<xsl:value-of select="string(.)"/>
														</url>
													</xsl:for-each>
													<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:address">
														<address>
															<xsl:value-of select="string(.)"/>
														</address>
													</xsl:for-each>
													<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:zipCode">
														<zipCode>
															<xsl:value-of select="string(.)"/>
														</zipCode>
													</xsl:for-each>
													<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:city">
														<city>
															<xsl:value-of select="string(.)"/>
														</city>
													</xsl:for-each>
													<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:country">
														<country>
															<xsl:value-of select="string(.)"/>
														</country>
													</xsl:for-each>
													<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:telephoneNumber">
														<telephoneNumber>
															<xsl:value-of select="string(.)"/>
														</telephoneNumber>
													</xsl:for-each>
													<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:faxNumber">
														<faxNumber>
															<xsl:value-of select="string(.)"/>
														</faxNumber>
													</xsl:for-each>
												</communicationInfo>
											</affiliation>
										</xsl:for-each>
									</personInfo>
								</xsl:for-each>
								<xsl:for-each select="ns0:OrganizationInfo">
									<organizationInfo>
										<organizationName>
											<xsl:variable name="var30_lang">
												<xsl:if test="ns0:organizationName/@ns0:lang">
													<xsl:value-of select="'1'"/>
												</xsl:if>
											</xsl:variable>
											<xsl:if test="string(boolean(string($var30_lang))) != 'false'">
												<xsl:attribute name="lang" namespace="">
													<xsl:value-of select="string(ns0:organizationName/@ns0:lang)"/>
												</xsl:attribute>
											</xsl:if>
											<xsl:value-of select="string(ns0:organizationName)"/>
										</organizationName>
										<xsl:for-each select="ns0:organizationShortName">
											<organizationShortName>
												<xsl:variable name="var31_lang">
													<xsl:if test="@ns0:lang">
														<xsl:value-of select="'1'"/>
													</xsl:if>
												</xsl:variable>
												<xsl:if test="string(boolean(string($var31_lang))) != 'false'">
													<xsl:attribute name="lang" namespace="">
														<xsl:value-of select="string(@ns0:lang)"/>
													</xsl:attribute>
												</xsl:if>
												<xsl:value-of select="string(.)"/>
											</organizationShortName>
										</xsl:for-each>
										<xsl:for-each select="ns0:departmentName">
											<departmentName>
												<xsl:variable name="var32_lang">
													<xsl:if test="@ns0:lang">
														<xsl:value-of select="'1'"/>
													</xsl:if>
												</xsl:variable>
												<xsl:if test="string(boolean(string($var32_lang))) != 'false'">
													<xsl:attribute name="lang" namespace="">
														<xsl:value-of select="string(@ns0:lang)"/>
													</xsl:attribute>
												</xsl:if>
												<xsl:value-of select="string(.)"/>
											</departmentName>
										</xsl:for-each>
										<communicationInfo>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:email">
												<email>
													<xsl:value-of select="string(.)"/>
												</email>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:url">
												<url>
													<xsl:value-of select="string(.)"/>
												</url>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:address">
												<address>
													<xsl:value-of select="string(.)"/>
												</address>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:zipCode">
												<zipCode>
													<xsl:value-of select="string(.)"/>
												</zipCode>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:city">
												<city>
													<xsl:value-of select="string(.)"/>
												</city>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:country">
												<country>
													<xsl:value-of select="string(.)"/>
												</country>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:telephoneNumber">
												<telephoneNumber>
													<xsl:value-of select="string(.)"/>
												</telephoneNumber>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:faxNumber">
												<faxNumber>
													<xsl:value-of select="string(.)"/>
												</faxNumber>
											</xsl:for-each>
										</communicationInfo>
									</organizationInfo>
								</xsl:for-each>
							</resourceCreator>
						</xsl:for-each>
						<xsl:for-each select="ns0:FundingInfo/ns0:ProjectInfo">
							<fundingProject>
								<projectName>
									<xsl:variable name="var33_lang">
										<xsl:if test="ns0:projectName/@ns0:lang">
											<xsl:value-of select="'1'"/>
										</xsl:if>
									</xsl:variable>
									<xsl:if test="string(boolean(string($var33_lang))) != 'false'">
										<xsl:attribute name="lang" namespace="">
											<xsl:value-of select="string(ns0:projectName/@ns0:lang)"/>
										</xsl:attribute>
									</xsl:if>
									<xsl:value-of select="string(ns0:projectName)"/>
								</projectName>
								<xsl:for-each select="ns0:projectShortName">
									<projectShortName>
										<xsl:variable name="var34_lang">
											<xsl:if test="@ns0:lang">
												<xsl:value-of select="'1'"/>
											</xsl:if>
										</xsl:variable>
										<xsl:if test="string(boolean(string($var34_lang))) != 'false'">
											<xsl:attribute name="lang" namespace="">
												<xsl:value-of select="string(@ns0:lang)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:value-of select="string(.)"/>
									</projectShortName>
								</xsl:for-each>
								<xsl:for-each select="ns0:projectID">
									<projectID>
										<xsl:value-of select="string(.)"/>
									</projectID>
								</xsl:for-each>
								<xsl:for-each select="ns0:url">
									<url>
										<xsl:value-of select="string(.)"/>
									</url>
								</xsl:for-each>
								<xsl:for-each select="ns0:fundingType">
									<fundingType>
										<xsl:value-of select="string(.)"/>
									</fundingType>
								</xsl:for-each>
								<xsl:for-each select="ns0:funder">
									<funder>
										<xsl:value-of select="string(.)"/>
									</funder>
								</xsl:for-each>
								<xsl:for-each select="ns0:fundingCountry">
									<fundingCountry>
										<xsl:value-of select="string(.)"/>
									</fundingCountry>
								</xsl:for-each>
								<xsl:for-each select="ns0:projectStartDate">
									<projectStartDate>
										<xsl:value-of select="string(.)"/>
									</projectStartDate>
								</xsl:for-each>
								<xsl:for-each select="ns0:projectEndDate">
									<projectEndDate>
										<xsl:value-of select="string(.)"/>
									</projectEndDate>
								</xsl:for-each>
							</fundingProject>
						</xsl:for-each>
						<xsl:for-each select="ns0:creationStartDate">
							<creationStartDate>
								<xsl:value-of select="string(.)"/>
							</creationStartDate>
						</xsl:for-each>
						<xsl:for-each select="ns0:creationEndDate">
							<creationEndDate>
								<xsl:value-of select="string(.)"/>
							</creationEndDate>
						</xsl:for-each>
					</resourceCreationInfo>
				</xsl:for-each>
				<resourceComponentType>
					<toolServiceInfo>
						<resourceType>toolService</resourceType>
						<toolServiceType>
							<xsl:value-of select="string(ns0:ToolServiceInfo/ns0:toolServiceType)"/>
						</toolServiceType>
						<xsl:for-each select="ns0:ToolServiceInfo/ns0:toolServiceSubtype">
							<toolServiceSubtype>
								<xsl:value-of select="string(.)"/>
							</toolServiceSubtype>
						</xsl:for-each>
						<languageDependent>
							<xsl:value-of select="string((translate(string(ns0:ToolServiceInfo/ns0:languageDependent), '1falseru0 ', 't') = 't'))"/>
						</languageDependent>
						<inputInfo>
							<xsl:for-each select="ns0:ToolServiceInfo/ns0:InputInfo/ns0:mediaType">
								<mediaType>
									<xsl:value-of select="string(.)"/>
								</mediaType>
							</xsl:for-each>
							<xsl:for-each select="ns0:ToolServiceInfo/ns0:InputInfo/ns0:resourceType">
								<resourceType>
									<xsl:value-of select="string(.)"/>
								</resourceType>
							</xsl:for-each>
							<xsl:for-each select="ns0:ToolServiceInfo/ns0:InputInfo/ns0:modalityType">
								<modalityType>
									<xsl:value-of select="string(.)"/>
								</modalityType>
							</xsl:for-each>
						</inputInfo>
						<outputInfo>
							<xsl:for-each select="ns0:ToolServiceInfo/ns0:OutputInfo/ns0:mediaType">
								<mediaType>
									<xsl:value-of select="string(.)"/>
								</mediaType>
							</xsl:for-each>
							<xsl:for-each select="ns0:ToolServiceInfo/ns0:OutputInfo/ns0:resourceType">
								<resourceType>
									<xsl:value-of select="string(.)"/>
								</resourceType>
							</xsl:for-each>
							<xsl:for-each select="ns0:ToolServiceInfo/ns0:OutputInfo/ns0:modalityType">
								<modalityType>
									<xsl:value-of select="string(.)"/>
								</modalityType>
							</xsl:for-each>
						</outputInfo>
						<xsl:for-each select="ns0:ToolServiceInfo/ns0:ToolServiceOperationInfo">
							<toolServiceOperationInfo>
								<xsl:for-each select="ns0:operatingSystem">
									<operatingSystem>
										<xsl:value-of select="string(.)"/>
									</operatingSystem>
								</xsl:for-each>
								<xsl:for-each select="ns0:runningTime">
									<runningTime>
										<xsl:value-of select="string(.)"/>
									</runningTime>
								</xsl:for-each>
							</toolServiceOperationInfo>
						</xsl:for-each>
						<xsl:for-each select="ns0:ToolServiceInfo/ns0:ToolServiceEvaluationInfo">
							<toolServiceEvaluationInfo>
								<evaluated>
									<xsl:value-of select="string((translate(string(ns0:evaluated), '1falseru0 ', 't') = 't'))"/>
								</evaluated>
								<xsl:for-each select="ns0:evaluationLevel">
									<evaluationLevel>
										<xsl:value-of select="string(.)"/>
									</evaluationLevel>
								</xsl:for-each>
								<xsl:for-each select="ns0:evaluationType">
									<evaluationType>
										<xsl:value-of select="string(.)"/>
									</evaluationType>
								</xsl:for-each>
								<xsl:for-each select="ns0:evaluationCriteria">
									<evaluationCriteria>
										<xsl:value-of select="string(.)"/>
									</evaluationCriteria>
								</xsl:for-each>
								<xsl:for-each select="ns0:evaluationMeasure">
									<evaluationMeasure>
										<xsl:value-of select="string(.)"/>
									</evaluationMeasure>
								</xsl:for-each>
								<xsl:for-each select="ns0:evaluationReport">
									<evaluationReport>
										<documentUnstructured>
											<xsl:value-of select="string(.)"/>
										</documentUnstructured>
									</evaluationReport>
								</xsl:for-each>
								<xsl:for-each select="ns0:evaluationTool">
									<evaluationTool>
										<xsl:value-of select="/.."/>
									</evaluationTool>
								</xsl:for-each>
								<xsl:for-each select="ns0:evaluationDetails">
									<evaluationDetails>
										<xsl:value-of select="string(.)"/>
									</evaluationDetails>
								</xsl:for-each>
								<xsl:for-each select="ns0:evaluator">
									<evaluator>
										<xsl:for-each select="ns0:PersonInfo">
											<personInfo>
												<xsl:for-each select="ns0:surname">
													<surname>
														<xsl:variable name="var35_lang">
															<xsl:if test="@ns0:lang">
																<xsl:value-of select="'1'"/>
															</xsl:if>
														</xsl:variable>
														<xsl:if test="string(boolean(string($var35_lang))) != 'false'">
															<xsl:attribute name="lang" namespace="">
																<xsl:value-of select="string(@ns0:lang)"/>
															</xsl:attribute>
														</xsl:if>
														<xsl:value-of select="string(.)"/>
													</surname>
												</xsl:for-each>
												<xsl:for-each select="ns0:givenName">
													<givenName>
														<xsl:variable name="var36_lang">
															<xsl:if test="@ns0:lang">
																<xsl:value-of select="'1'"/>
															</xsl:if>
														</xsl:variable>
														<xsl:if test="string(boolean(string($var36_lang))) != 'false'">
															<xsl:attribute name="lang" namespace="">
																<xsl:value-of select="string(@ns0:lang)"/>
															</xsl:attribute>
														</xsl:if>
														<xsl:value-of select="string(.)"/>
													</givenName>
												</xsl:for-each>
												<communicationInfo>
													<xsl:for-each select="ns0:CommunicationInfo/ns0:email">
														<email>
															<xsl:value-of select="string(.)"/>
														</email>
													</xsl:for-each>
													<xsl:for-each select="ns0:CommunicationInfo/ns0:url">
														<url>
															<xsl:value-of select="string(.)"/>
														</url>
													</xsl:for-each>
													<xsl:for-each select="ns0:CommunicationInfo/ns0:address">
														<address>
															<xsl:value-of select="string(.)"/>
														</address>
													</xsl:for-each>
													<xsl:for-each select="ns0:CommunicationInfo/ns0:zipCode">
														<zipCode>
															<xsl:value-of select="string(.)"/>
														</zipCode>
													</xsl:for-each>
													<xsl:for-each select="ns0:CommunicationInfo/ns0:city">
														<city>
															<xsl:value-of select="string(.)"/>
														</city>
													</xsl:for-each>
													<xsl:for-each select="ns0:CommunicationInfo/ns0:country">
														<country>
															<xsl:value-of select="string(.)"/>
														</country>
													</xsl:for-each>
													<xsl:for-each select="ns0:CommunicationInfo/ns0:telephoneNumber">
														<telephoneNumber>
															<xsl:value-of select="string(.)"/>
														</telephoneNumber>
													</xsl:for-each>
													<xsl:for-each select="ns0:CommunicationInfo/ns0:faxNumber">
														<faxNumber>
															<xsl:value-of select="string(.)"/>
														</faxNumber>
													</xsl:for-each>
												</communicationInfo>
												<xsl:for-each select="ns0:position">
													<position>
														<xsl:value-of select="string(.)"/>
													</position>
												</xsl:for-each>
												<xsl:for-each select="ns0:affiliation">
													<affiliation>
														<organizationName>
															<xsl:variable name="var37_lang">
																<xsl:if test="ns0:OrganizationInfo/ns0:organizationName/@ns0:lang">
																	<xsl:value-of select="'1'"/>
																</xsl:if>
															</xsl:variable>
															<xsl:if test="string(boolean(string($var37_lang))) != 'false'">
																<xsl:attribute name="lang" namespace="">
																	<xsl:value-of select="string(ns0:OrganizationInfo/ns0:organizationName/@ns0:lang)"/>
																</xsl:attribute>
															</xsl:if>
															<xsl:value-of select="string(ns0:OrganizationInfo/ns0:organizationName)"/>
														</organizationName>
														<xsl:for-each select="ns0:OrganizationInfo/ns0:organizationShortName">
															<organizationShortName>
																<xsl:variable name="var38_lang">
																	<xsl:if test="@ns0:lang">
																		<xsl:value-of select="'1'"/>
																	</xsl:if>
																</xsl:variable>
																<xsl:if test="string(boolean(string($var38_lang))) != 'false'">
																	<xsl:attribute name="lang" namespace="">
																		<xsl:value-of select="string(@ns0:lang)"/>
																	</xsl:attribute>
																</xsl:if>
																<xsl:value-of select="string(.)"/>
															</organizationShortName>
														</xsl:for-each>
														<xsl:for-each select="ns0:OrganizationInfo/ns0:departmentName">
															<departmentName>
																<xsl:variable name="var39_lang">
																	<xsl:if test="@ns0:lang">
																		<xsl:value-of select="'1'"/>
																	</xsl:if>
																</xsl:variable>
																<xsl:if test="string(boolean(string($var39_lang))) != 'false'">
																	<xsl:attribute name="lang" namespace="">
																		<xsl:value-of select="string(@ns0:lang)"/>
																	</xsl:attribute>
																</xsl:if>
																<xsl:value-of select="string(.)"/>
															</departmentName>
														</xsl:for-each>
														<communicationInfo>
															<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:email">
																<email>
																	<xsl:value-of select="string(.)"/>
																</email>
															</xsl:for-each>
															<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:url">
																<url>
																	<xsl:value-of select="string(.)"/>
																</url>
															</xsl:for-each>
															<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:address">
																<address>
																	<xsl:value-of select="string(.)"/>
																</address>
															</xsl:for-each>
															<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:zipCode">
																<zipCode>
																	<xsl:value-of select="string(.)"/>
																</zipCode>
															</xsl:for-each>
															<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:city">
																<city>
																	<xsl:value-of select="string(.)"/>
																</city>
															</xsl:for-each>
															<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:country">
																<country>
																	<xsl:value-of select="string(.)"/>
																</country>
															</xsl:for-each>
															<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:telephoneNumber">
																<telephoneNumber>
																	<xsl:value-of select="string(.)"/>
																</telephoneNumber>
															</xsl:for-each>
															<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:faxNumber">
																<faxNumber>
																	<xsl:value-of select="string(.)"/>
																</faxNumber>
															</xsl:for-each>
														</communicationInfo>
													</affiliation>
												</xsl:for-each>
											</personInfo>
										</xsl:for-each>
										<xsl:for-each select="ns0:OrganizationInfo">
											<organizationInfo>
												<organizationName>
													<xsl:variable name="var40_lang">
														<xsl:if test="ns0:organizationName/@ns0:lang">
															<xsl:value-of select="'1'"/>
														</xsl:if>
													</xsl:variable>
													<xsl:if test="string(boolean(string($var40_lang))) != 'false'">
														<xsl:attribute name="lang" namespace="">
															<xsl:value-of select="string(ns0:organizationName/@ns0:lang)"/>
														</xsl:attribute>
													</xsl:if>
													<xsl:value-of select="string(ns0:organizationName)"/>
												</organizationName>
												<xsl:for-each select="ns0:organizationShortName">
													<organizationShortName>
														<xsl:variable name="var41_lang">
															<xsl:if test="@ns0:lang">
																<xsl:value-of select="'1'"/>
															</xsl:if>
														</xsl:variable>
														<xsl:if test="string(boolean(string($var41_lang))) != 'false'">
															<xsl:attribute name="lang" namespace="">
																<xsl:value-of select="string(@ns0:lang)"/>
															</xsl:attribute>
														</xsl:if>
														<xsl:value-of select="string(.)"/>
													</organizationShortName>
												</xsl:for-each>
												<xsl:for-each select="ns0:departmentName">
													<departmentName>
														<xsl:variable name="var42_lang">
															<xsl:if test="@ns0:lang">
																<xsl:value-of select="'1'"/>
															</xsl:if>
														</xsl:variable>
														<xsl:if test="string(boolean(string($var42_lang))) != 'false'">
															<xsl:attribute name="lang" namespace="">
																<xsl:value-of select="string(@ns0:lang)"/>
															</xsl:attribute>
														</xsl:if>
														<xsl:value-of select="string(.)"/>
													</departmentName>
												</xsl:for-each>
												<communicationInfo>
													<xsl:for-each select="ns0:CommunicationInfo/ns0:email">
														<email>
															<xsl:value-of select="string(.)"/>
														</email>
													</xsl:for-each>
													<xsl:for-each select="ns0:CommunicationInfo/ns0:url">
														<url>
															<xsl:value-of select="string(.)"/>
														</url>
													</xsl:for-each>
													<xsl:for-each select="ns0:CommunicationInfo/ns0:address">
														<address>
															<xsl:value-of select="string(.)"/>
														</address>
													</xsl:for-each>
													<xsl:for-each select="ns0:CommunicationInfo/ns0:zipCode">
														<zipCode>
															<xsl:value-of select="string(.)"/>
														</zipCode>
													</xsl:for-each>
													<xsl:for-each select="ns0:CommunicationInfo/ns0:city">
														<city>
															<xsl:value-of select="string(.)"/>
														</city>
													</xsl:for-each>
													<xsl:for-each select="ns0:CommunicationInfo/ns0:country">
														<country>
															<xsl:value-of select="string(.)"/>
														</country>
													</xsl:for-each>
													<xsl:for-each select="ns0:CommunicationInfo/ns0:telephoneNumber">
														<telephoneNumber>
															<xsl:value-of select="string(.)"/>
														</telephoneNumber>
													</xsl:for-each>
													<xsl:for-each select="ns0:CommunicationInfo/ns0:faxNumber">
														<faxNumber>
															<xsl:value-of select="string(.)"/>
														</faxNumber>
													</xsl:for-each>
												</communicationInfo>
											</organizationInfo>
										</xsl:for-each>
									</evaluator>
								</xsl:for-each>
							</toolServiceEvaluationInfo>
						</xsl:for-each>
						<xsl:for-each select="ns0:ToolServiceInfo/ns0:ToolServiceCreationInfo">
							<toolServiceCreationInfo>
								<xsl:for-each select="ns0:implementationLanguage">
									<implementationLanguage>
										<xsl:value-of select="string(.)"/>
									</implementationLanguage>
								</xsl:for-each>
								<xsl:for-each select="ns0:formalism">
									<formalism>
										<xsl:value-of select="string(.)"/>
									</formalism>
								</xsl:for-each>
								<xsl:for-each select="ns0:creationDetails">
									<creationDetails>
										<xsl:value-of select="string(.)"/>
									</creationDetails>
								</xsl:for-each>
							</toolServiceCreationInfo>
						</xsl:for-each>
					</toolServiceInfo>
				</resourceComponentType>
			</xsl:for-each>
		</resourceInfo>
	</xsl:template>
</xsl:stylesheet>
