<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2012r2

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:agt="http://www.altova.com/Mapforce/agt" xmlns:ns0="http://www.ilsp.gr/META-XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="agt ns0 xs">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template name="agt:var3_MapToMETA-SHARE-Resource_function">
		<xsl:param name="par0"/>
		<xsl:attribute name="lang">
			<xsl:value-of select="string($par0/@ns0:lang)"/>
		</xsl:attribute>
	</xsl:template>
	<xsl:template name="agt:var6_MapToMETA-SHARE-Resource_function">
		<xsl:param name="par0"/>
		<metaShareId xmlns="http://www.ilsp.gr/META-XMLSchema">
			<xsl:value-of select="$par0"/>
		</metaShareId>
	</xsl:template>
	<xsl:template name="agt:var8_MapToMETA-SHARE-Resource_function">
		<xsl:param name="par0"/>
		<identifier xmlns="http://www.ilsp.gr/META-XMLSchema">
			<xsl:value-of select="$par0"/>
		</identifier>
	</xsl:template>
	<xsl:template match="/">
		<resourceInfo xmlns="http://www.ilsp.gr/META-XMLSchema">
			<xsl:attribute name="xsi:schemaLocation" namespace="http://www.w3.org/2001/XMLSchema-instance">http://www.ilsp.gr/META-XMLSchema C:/develop/metashare/transform/schemaTransform/v2.0/META-SHARE-Resource.xsd</xsl:attribute>
			<xsl:for-each select="ns0:Resource">
				<identificationInfo>
					<resourceName>
						<xsl:variable name="var1_lang">
							<xsl:if test="ns0:IdentificationInfo/ns0:resourceName/@ns0:lang">
								<xsl:value-of select="'1'"/>
							</xsl:if>
						</xsl:variable>
						<xsl:if test="string(boolean(string($var1_lang))) != 'false'">
							<xsl:attribute name="lang" namespace="">
								<xsl:value-of select="string(ns0:IdentificationInfo/ns0:resourceName/@ns0:lang)"/>
							</xsl:attribute>
						</xsl:if>
						<xsl:value-of select="string(ns0:IdentificationInfo/ns0:resourceName)"/>
					</resourceName>
					<resourceShortName>
						<xsl:for-each select="ns0:IdentificationInfo/ns0:resourceShortName">
							<xsl:variable name="var2_lang">
								<xsl:if test="@ns0:lang">
									<xsl:value-of select="'1'"/>
								</xsl:if>
							</xsl:variable>
							<xsl:if test="string(boolean(string($var2_lang))) != 'false'">
								<xsl:call-template name="agt:var3_MapToMETA-SHARE-Resource_function">
									<xsl:with-param name="par0" select="."/>
								</xsl:call-template>
							</xsl:if>
						</xsl:for-each>
						<xsl:variable name="var4_resourceShortName">
							<xsl:if test="ns0:IdentificationInfo/ns0:resourceShortName">
								<xsl:value-of select="'1'"/>
							</xsl:if>
						</xsl:variable>
						<xsl:choose>
							<xsl:when test="string(boolean(string($var4_resourceShortName))) != 'false'">
								<xsl:value-of select="string(ns0:IdentificationInfo/ns0:resourceShortName)"/>
							</xsl:when>
							<xsl:otherwise>
								<xsl:value-of select="'n/a'"/>
							</xsl:otherwise>
						</xsl:choose>
					</resourceShortName>
					<xsl:for-each select="ns0:IdentificationInfo/ns0:url">
						<url>
							<xsl:value-of select="string(.)"/>
						</url>
					</xsl:for-each>
					<xsl:variable name="var5_identifier">
						<xsl:if test="ns0:IdentificationInfo/ns0:identifier">
							<xsl:value-of select="'1'"/>
						</xsl:if>
					</xsl:variable>
					<xsl:choose>
						<xsl:when test="string(boolean(string($var5_identifier))) != 'false'">
							<xsl:for-each select="ns0:IdentificationInfo/ns0:identifier">
								<xsl:call-template name="agt:var6_MapToMETA-SHARE-Resource_function">
									<xsl:with-param name="par0" select="string(.)"/>
								</xsl:call-template>
							</xsl:for-each>
						</xsl:when>
						<xsl:otherwise>
							<xsl:call-template name="agt:var6_MapToMETA-SHARE-Resource_function">
								<xsl:with-param name="par0" select="'n/a'"/>
							</xsl:call-template>
						</xsl:otherwise>
					</xsl:choose>
					<xsl:variable name="var7_identifier">
						<xsl:if test="ns0:IdentificationInfo/ns0:identifier">
							<xsl:value-of select="'1'"/>
						</xsl:if>
					</xsl:variable>
					<xsl:choose>
						<xsl:when test="string(boolean(string($var7_identifier))) != 'false'">
							<xsl:for-each select="ns0:IdentificationInfo/ns0:identifier">
								<xsl:call-template name="agt:var8_MapToMETA-SHARE-Resource_function">
									<xsl:with-param name="par0" select="string(.)"/>
								</xsl:call-template>
							</xsl:for-each>
						</xsl:when>
						<xsl:otherwise>
							<xsl:call-template name="agt:var8_MapToMETA-SHARE-Resource_function">
								<xsl:with-param name="par0" select="'n/a'"/>
							</xsl:call-template>
						</xsl:otherwise>
					</xsl:choose>
				</identificationInfo>
				<distributionInfo>
					<availability>available-restrictedUse</availability>
					<xsl:for-each select="ns0:DistributionInfo/ns0:iprHolder">
						<xsl:variable name="var17_cur" select="."/>
						<iprHolder>
							<xsl:for-each select="ns0:PersonInfo">
								<personInfo>
									<xsl:for-each select="ns0:surname">
										<surname>
											<xsl:variable name="var9_lang">
												<xsl:if test="@ns0:lang">
													<xsl:value-of select="'1'"/>
												</xsl:if>
											</xsl:variable>
											<xsl:if test="string(boolean(string($var9_lang))) != 'false'">
												<xsl:attribute name="lang" namespace="">
													<xsl:value-of select="string(@ns0:lang)"/>
												</xsl:attribute>
											</xsl:if>
											<xsl:value-of select="string(.)"/>
										</surname>
									</xsl:for-each>
									<xsl:for-each select="ns0:givenName">
										<givenName>
											<xsl:variable name="var10_lang">
												<xsl:if test="@ns0:lang">
													<xsl:value-of select="'1'"/>
												</xsl:if>
											</xsl:variable>
											<xsl:if test="string(boolean(string($var10_lang))) != 'false'">
												<xsl:attribute name="lang" namespace="">
													<xsl:value-of select="string(@ns0:lang)"/>
												</xsl:attribute>
											</xsl:if>
											<xsl:value-of select="string(.)"/>
										</givenName>
									</xsl:for-each>
									<communicationInfo>
										<xsl:for-each select="ns0:CommunicationInfo/ns0:email">
											<email>
												<xsl:value-of select="string(.)"/>
											</email>
										</xsl:for-each>
										<xsl:for-each select="$var17_cur/ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:email">
											<url>
												<xsl:value-of select="string(.)"/>
											</url>
										</xsl:for-each>
										<xsl:for-each select="$var17_cur/ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:address">
											<address>
												<xsl:value-of select="string(.)"/>
											</address>
										</xsl:for-each>
										<xsl:for-each select="$var17_cur/ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:zipCode">
											<zipCode>
												<xsl:value-of select="string(.)"/>
											</zipCode>
										</xsl:for-each>
										<xsl:for-each select="ns0:CommunicationInfo/ns0:city">
											<city>
												<xsl:value-of select="string(.)"/>
											</city>
										</xsl:for-each>
										<xsl:for-each select="ns0:CommunicationInfo/ns0:country">
											<country>
												<xsl:value-of select="string(.)"/>
											</country>
										</xsl:for-each>
										<xsl:for-each select="ns0:CommunicationInfo/ns0:telephoneNumber">
											<telephoneNumber>
												<xsl:value-of select="string(.)"/>
											</telephoneNumber>
										</xsl:for-each>
										<xsl:for-each select="ns0:CommunicationInfo/ns0:faxNumber">
											<faxNumber>
												<xsl:value-of select="string(.)"/>
											</faxNumber>
										</xsl:for-each>
									</communicationInfo>
									<xsl:for-each select="ns0:position">
										<position>
											<xsl:value-of select="string(.)"/>
										</position>
									</xsl:for-each>
									<xsl:for-each select="ns0:affiliation">
										<affiliation>
											<organizationName>
												<xsl:variable name="var11_lang">
													<xsl:if test="ns0:OrganizationInfo/ns0:organizationName/@ns0:lang">
														<xsl:value-of select="'1'"/>
													</xsl:if>
												</xsl:variable>
												<xsl:if test="string(boolean(string($var11_lang))) != 'false'">
													<xsl:attribute name="lang" namespace="">
														<xsl:value-of select="string(ns0:OrganizationInfo/ns0:organizationName/@ns0:lang)"/>
													</xsl:attribute>
												</xsl:if>
												<xsl:value-of select="string(ns0:OrganizationInfo/ns0:organizationName)"/>
											</organizationName>
											<xsl:for-each select="ns0:OrganizationInfo/ns0:organizationShortName">
												<organizationShortName>
													<xsl:variable name="var12_lang">
														<xsl:if test="@ns0:lang">
															<xsl:value-of select="'1'"/>
														</xsl:if>
													</xsl:variable>
													<xsl:if test="string(boolean(string($var12_lang))) != 'false'">
														<xsl:attribute name="lang" namespace="">
															<xsl:value-of select="string(@ns0:lang)"/>
														</xsl:attribute>
													</xsl:if>
													<xsl:value-of select="string(.)"/>
												</organizationShortName>
											</xsl:for-each>
											<xsl:for-each select="ns0:OrganizationInfo/ns0:departmentName">
												<departmentName>
													<xsl:variable name="var13_lang">
														<xsl:if test="@ns0:lang">
															<xsl:value-of select="'1'"/>
														</xsl:if>
													</xsl:variable>
													<xsl:if test="string(boolean(string($var13_lang))) != 'false'">
														<xsl:attribute name="lang" namespace="">
															<xsl:value-of select="string(@ns0:lang)"/>
														</xsl:attribute>
													</xsl:if>
													<xsl:value-of select="string(.)"/>
												</departmentName>
											</xsl:for-each>
											<communicationInfo>
												<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:email">
													<email>
														<xsl:value-of select="string(.)"/>
													</email>
												</xsl:for-each>
												<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:url">
													<url>
														<xsl:value-of select="string(.)"/>
													</url>
												</xsl:for-each>
												<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:address">
													<address>
														<xsl:value-of select="string(.)"/>
													</address>
												</xsl:for-each>
												<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:zipCode">
													<zipCode>
														<xsl:value-of select="string(.)"/>
													</zipCode>
												</xsl:for-each>
												<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:city">
													<city>
														<xsl:value-of select="string(.)"/>
													</city>
												</xsl:for-each>
												<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:country">
													<country>
														<xsl:value-of select="string(.)"/>
													</country>
												</xsl:for-each>
												<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:telephoneNumber">
													<telephoneNumber>
														<xsl:value-of select="string(.)"/>
													</telephoneNumber>
												</xsl:for-each>
												<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:faxNumber">
													<faxNumber>
														<xsl:value-of select="string(.)"/>
													</faxNumber>
												</xsl:for-each>
											</communicationInfo>
										</affiliation>
									</xsl:for-each>
								</personInfo>
							</xsl:for-each>
							<xsl:for-each select="ns0:OrganizationInfo">
								<organizationInfo>
									<organizationName>
										<xsl:variable name="var14_lang">
											<xsl:if test="ns0:organizationName/@ns0:lang">
												<xsl:value-of select="'1'"/>
											</xsl:if>
										</xsl:variable>
										<xsl:if test="string(boolean(string($var14_lang))) != 'false'">
											<xsl:attribute name="lang" namespace="">
												<xsl:value-of select="string(ns0:organizationName/@ns0:lang)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:value-of select="string(ns0:organizationName)"/>
									</organizationName>
									<xsl:for-each select="ns0:organizationShortName">
										<organizationShortName>
											<xsl:variable name="var15_lang">
												<xsl:if test="@ns0:lang">
													<xsl:value-of select="'1'"/>
												</xsl:if>
											</xsl:variable>
											<xsl:if test="string(boolean(string($var15_lang))) != 'false'">
												<xsl:attribute name="lang" namespace="">
													<xsl:value-of select="string(@ns0:lang)"/>
												</xsl:attribute>
											</xsl:if>
											<xsl:value-of select="string(.)"/>
										</organizationShortName>
									</xsl:for-each>
									<xsl:for-each select="ns0:departmentName">
										<departmentName>
											<xsl:variable name="var16_lang">
												<xsl:if test="@ns0:lang">
													<xsl:value-of select="'1'"/>
												</xsl:if>
											</xsl:variable>
											<xsl:if test="string(boolean(string($var16_lang))) != 'false'">
												<xsl:attribute name="lang" namespace="">
													<xsl:value-of select="string(@ns0:lang)"/>
												</xsl:attribute>
											</xsl:if>
											<xsl:value-of select="string(.)"/>
										</departmentName>
									</xsl:for-each>
									<communicationInfo>
										<xsl:for-each select="ns0:CommunicationInfo/ns0:email">
											<email>
												<xsl:value-of select="string(.)"/>
											</email>
										</xsl:for-each>
										<xsl:for-each select="ns0:CommunicationInfo/ns0:url">
											<url>
												<xsl:value-of select="string(.)"/>
											</url>
										</xsl:for-each>
										<xsl:for-each select="ns0:CommunicationInfo/ns0:address">
											<address>
												<xsl:value-of select="string(.)"/>
											</address>
										</xsl:for-each>
										<xsl:for-each select="ns0:CommunicationInfo/ns0:zipCode">
											<zipCode>
												<xsl:value-of select="string(.)"/>
											</zipCode>
										</xsl:for-each>
										<xsl:for-each select="ns0:CommunicationInfo/ns0:city">
											<city>
												<xsl:value-of select="string(.)"/>
											</city>
										</xsl:for-each>
										<xsl:for-each select="ns0:CommunicationInfo/ns0:country">
											<country>
												<xsl:value-of select="string(.)"/>
											</country>
										</xsl:for-each>
										<xsl:for-each select="ns0:CommunicationInfo/ns0:telephoneNumber">
											<telephoneNumber>
												<xsl:value-of select="string(.)"/>
											</telephoneNumber>
										</xsl:for-each>
										<xsl:for-each select="ns0:CommunicationInfo/ns0:faxNumber">
											<faxNumber>
												<xsl:value-of select="string(.)"/>
											</faxNumber>
										</xsl:for-each>
									</communicationInfo>
								</organizationInfo>
							</xsl:for-each>
						</iprHolder>
					</xsl:for-each>
				</distributionInfo>
				<xsl:for-each select="ns0:contactPerson">
					<contactPerson>
						<xsl:for-each select="ns0:surname">
							<surname>
								<xsl:variable name="var18_lang">
									<xsl:if test="@ns0:lang">
										<xsl:value-of select="'1'"/>
									</xsl:if>
								</xsl:variable>
								<xsl:if test="string(boolean(string($var18_lang))) != 'false'">
									<xsl:attribute name="lang" namespace="">
										<xsl:value-of select="string(@ns0:lang)"/>
									</xsl:attribute>
								</xsl:if>
								<xsl:value-of select="string(.)"/>
							</surname>
						</xsl:for-each>
						<xsl:for-each select="ns0:givenName">
							<givenName>
								<xsl:variable name="var19_lang">
									<xsl:if test="@ns0:lang">
										<xsl:value-of select="'1'"/>
									</xsl:if>
								</xsl:variable>
								<xsl:if test="string(boolean(string($var19_lang))) != 'false'">
									<xsl:attribute name="lang" namespace="">
										<xsl:value-of select="string(@ns0:lang)"/>
									</xsl:attribute>
								</xsl:if>
								<xsl:value-of select="string(.)"/>
							</givenName>
						</xsl:for-each>
						<communicationInfo>
							<xsl:for-each select="ns0:CommunicationInfo/ns0:email">
								<email>
									<xsl:value-of select="string(.)"/>
								</email>
							</xsl:for-each>
							<xsl:for-each select="ns0:CommunicationInfo/ns0:url">
								<url>
									<xsl:value-of select="string(.)"/>
								</url>
							</xsl:for-each>
							<xsl:for-each select="ns0:CommunicationInfo/ns0:address">
								<address>
									<xsl:value-of select="string(.)"/>
								</address>
							</xsl:for-each>
							<xsl:for-each select="ns0:CommunicationInfo/ns0:zipCode">
								<zipCode>
									<xsl:value-of select="string(.)"/>
								</zipCode>
							</xsl:for-each>
							<xsl:for-each select="ns0:CommunicationInfo/ns0:city">
								<city>
									<xsl:value-of select="string(.)"/>
								</city>
							</xsl:for-each>
							<xsl:for-each select="ns0:CommunicationInfo/ns0:country">
								<country>
									<xsl:value-of select="string(.)"/>
								</country>
							</xsl:for-each>
							<xsl:for-each select="ns0:CommunicationInfo/ns0:telephoneNumber">
								<telephoneNumber>
									<xsl:value-of select="string(.)"/>
								</telephoneNumber>
							</xsl:for-each>
							<xsl:for-each select="ns0:CommunicationInfo/ns0:faxNumber">
								<faxNumber>
									<xsl:value-of select="string(.)"/>
								</faxNumber>
							</xsl:for-each>
						</communicationInfo>
						<xsl:for-each select="ns0:position">
							<position>
								<xsl:value-of select="string(.)"/>
							</position>
						</xsl:for-each>
						<xsl:for-each select="ns0:affiliation">
							<affiliation>
								<organizationName>
									<xsl:variable name="var20_lang">
										<xsl:if test="ns0:OrganizationInfo/ns0:organizationName/@ns0:lang">
											<xsl:value-of select="'1'"/>
										</xsl:if>
									</xsl:variable>
									<xsl:if test="string(boolean(string($var20_lang))) != 'false'">
										<xsl:attribute name="lang" namespace="">
											<xsl:value-of select="string(ns0:OrganizationInfo/ns0:organizationName/@ns0:lang)"/>
										</xsl:attribute>
									</xsl:if>
									<xsl:value-of select="string(ns0:OrganizationInfo/ns0:organizationName)"/>
								</organizationName>
								<xsl:for-each select="ns0:OrganizationInfo/ns0:departmentName">
									<departmentName>
										<xsl:variable name="var21_lang">
											<xsl:if test="@ns0:lang">
												<xsl:value-of select="'1'"/>
											</xsl:if>
										</xsl:variable>
										<xsl:if test="string(boolean(string($var21_lang))) != 'false'">
											<xsl:attribute name="lang" namespace="">
												<xsl:value-of select="string(@ns0:lang)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:value-of select="string(.)"/>
									</departmentName>
								</xsl:for-each>
								<communicationInfo>
									<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:email">
										<email>
											<xsl:value-of select="string(.)"/>
										</email>
									</xsl:for-each>
									<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:url">
										<url>
											<xsl:value-of select="string(.)"/>
										</url>
									</xsl:for-each>
									<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:address">
										<address>
											<xsl:value-of select="string(.)"/>
										</address>
									</xsl:for-each>
									<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:zipCode">
										<zipCode>
											<xsl:value-of select="string(.)"/>
										</zipCode>
									</xsl:for-each>
									<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:city">
										<city>
											<xsl:value-of select="string(.)"/>
										</city>
									</xsl:for-each>
									<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:country">
										<country>
											<xsl:value-of select="string(.)"/>
										</country>
									</xsl:for-each>
									<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:telephoneNumber">
										<telephoneNumber>
											<xsl:value-of select="string(.)"/>
										</telephoneNumber>
									</xsl:for-each>
									<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:faxNumber">
										<faxNumber>
											<xsl:value-of select="string(.)"/>
										</faxNumber>
									</xsl:for-each>
								</communicationInfo>
							</affiliation>
						</xsl:for-each>
					</contactPerson>
				</xsl:for-each>
				<metadataInfo>
					<metadataCreationDate>
						<xsl:value-of select="string(ns0:MetadataInfo/ns0:metadataCreationDate)"/>
					</metadataCreationDate>
					<xsl:for-each select="ns0:MetadataInfo/ns0:metadataCreator">
						<xsl:variable name="var27_cur" select="."/>
						<metadataCreator>
							<xsl:for-each select="ns0:surname">
								<surname>
									<xsl:variable name="var22_lang">
										<xsl:if test="@ns0:lang">
											<xsl:value-of select="'1'"/>
										</xsl:if>
									</xsl:variable>
									<xsl:if test="string(boolean(string($var22_lang))) != 'false'">
										<xsl:attribute name="lang" namespace="">
											<xsl:value-of select="string(@ns0:lang)"/>
										</xsl:attribute>
									</xsl:if>
									<xsl:value-of select="string(.)"/>
								</surname>
							</xsl:for-each>
							<xsl:for-each select="ns0:givenName">
								<givenName>
									<xsl:variable name="var23_lang">
										<xsl:if test="@ns0:lang">
											<xsl:value-of select="'1'"/>
										</xsl:if>
									</xsl:variable>
									<xsl:if test="string(boolean(string($var23_lang))) != 'false'">
										<xsl:attribute name="lang" namespace="">
											<xsl:value-of select="string(@ns0:lang)"/>
										</xsl:attribute>
									</xsl:if>
									<xsl:value-of select="string(.)"/>
								</givenName>
							</xsl:for-each>
							<communicationInfo>
								<xsl:for-each select="ns0:CommunicationInfo/ns0:email">
									<email>
										<xsl:value-of select="string(.)"/>
									</email>
								</xsl:for-each>
								<xsl:for-each select="ns0:CommunicationInfo/ns0:url">
									<url>
										<xsl:value-of select="string(.)"/>
									</url>
								</xsl:for-each>
								<xsl:for-each select="ns0:CommunicationInfo/ns0:address">
									<address>
										<xsl:value-of select="string(.)"/>
									</address>
								</xsl:for-each>
								<xsl:for-each select="ns0:CommunicationInfo/ns0:zipCode">
									<zipCode>
										<xsl:value-of select="string(.)"/>
									</zipCode>
								</xsl:for-each>
								<xsl:for-each select="ns0:CommunicationInfo/ns0:city">
									<city>
										<xsl:value-of select="string(.)"/>
									</city>
								</xsl:for-each>
								<xsl:for-each select="ns0:CommunicationInfo/ns0:country">
									<country>
										<xsl:value-of select="string(.)"/>
									</country>
								</xsl:for-each>
								<xsl:for-each select="ns0:CommunicationInfo/ns0:telephoneNumber">
									<telephoneNumber>
										<xsl:value-of select="string(.)"/>
									</telephoneNumber>
								</xsl:for-each>
								<xsl:for-each select="ns0:CommunicationInfo/ns0:faxNumber">
									<faxNumber>
										<xsl:value-of select="string(.)"/>
									</faxNumber>
								</xsl:for-each>
							</communicationInfo>
							<xsl:for-each select="ns0:position">
								<position>
									<xsl:value-of select="string(.)"/>
								</position>
							</xsl:for-each>
							<xsl:for-each select="ns0:affiliation">
								<affiliation>
									<organizationName>
										<xsl:variable name="var24_lang">
											<xsl:if test="ns0:OrganizationInfo/ns0:organizationName/@ns0:lang">
												<xsl:value-of select="'1'"/>
											</xsl:if>
										</xsl:variable>
										<xsl:if test="string(boolean(string($var24_lang))) != 'false'">
											<xsl:attribute name="lang" namespace="">
												<xsl:value-of select="string(ns0:OrganizationInfo/ns0:organizationName/@ns0:lang)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:value-of select="string(ns0:OrganizationInfo/ns0:organizationName)"/>
									</organizationName>
									<xsl:for-each select="ns0:OrganizationInfo/ns0:organizationShortName">
										<organizationShortName>
											<xsl:variable name="var25_lang">
												<xsl:if test="@ns0:lang">
													<xsl:value-of select="'1'"/>
												</xsl:if>
											</xsl:variable>
											<xsl:if test="string(boolean(string($var25_lang))) != 'false'">
												<xsl:attribute name="lang" namespace="">
													<xsl:value-of select="string(@ns0:lang)"/>
												</xsl:attribute>
											</xsl:if>
											<xsl:value-of select="string(.)"/>
										</organizationShortName>
									</xsl:for-each>
									<xsl:for-each select="ns0:OrganizationInfo/ns0:departmentName">
										<departmentName>
											<xsl:variable name="var26_lang">
												<xsl:if test="@ns0:lang">
													<xsl:value-of select="'1'"/>
												</xsl:if>
											</xsl:variable>
											<xsl:if test="string(boolean(string($var26_lang))) != 'false'">
												<xsl:attribute name="lang" namespace="">
													<xsl:value-of select="string(@ns0:lang)"/>
												</xsl:attribute>
											</xsl:if>
											<xsl:value-of select="string(.)"/>
										</departmentName>
									</xsl:for-each>
									<communicationInfo>
										<xsl:for-each select="$var27_cur/ns0:CommunicationInfo/ns0:email">
											<email>
												<xsl:value-of select="string(.)"/>
											</email>
										</xsl:for-each>
										<xsl:for-each select="$var27_cur/ns0:CommunicationInfo/ns0:url">
											<url>
												<xsl:value-of select="string(.)"/>
											</url>
										</xsl:for-each>
										<xsl:for-each select="$var27_cur/ns0:CommunicationInfo/ns0:address">
											<address>
												<xsl:value-of select="string(.)"/>
											</address>
										</xsl:for-each>
										<xsl:for-each select="$var27_cur/ns0:CommunicationInfo/ns0:zipCode">
											<zipCode>
												<xsl:value-of select="string(.)"/>
											</zipCode>
										</xsl:for-each>
										<xsl:for-each select="$var27_cur/ns0:CommunicationInfo/ns0:city">
											<city>
												<xsl:value-of select="string(.)"/>
											</city>
										</xsl:for-each>
										<xsl:for-each select="$var27_cur/ns0:CommunicationInfo/ns0:country">
											<country>
												<xsl:value-of select="string(.)"/>
											</country>
										</xsl:for-each>
										<xsl:for-each select="$var27_cur/ns0:CommunicationInfo/ns0:telephoneNumber">
											<telephoneNumber>
												<xsl:value-of select="string(.)"/>
											</telephoneNumber>
										</xsl:for-each>
										<xsl:for-each select="$var27_cur/ns0:CommunicationInfo/ns0:faxNumber">
											<faxNumber>
												<xsl:value-of select="string(.)"/>
											</faxNumber>
										</xsl:for-each>
									</communicationInfo>
								</affiliation>
							</xsl:for-each>
						</metadataCreator>
					</xsl:for-each>
					<xsl:for-each select="ns0:MetadataInfo/ns0:source">
						<source>
							<xsl:value-of select="string(.)"/>
						</source>
					</xsl:for-each>
					<xsl:for-each select="ns0:MetadataInfo/ns0:originalMetadataSchema">
						<originalMetadataSchema>
							<xsl:value-of select="string(.)"/>
						</originalMetadataSchema>
					</xsl:for-each>
					<xsl:for-each select="ns0:MetadataInfo/ns0:originalMetadataLink">
						<originalMetadataLink>
							<xsl:value-of select="string(.)"/>
						</originalMetadataLink>
					</xsl:for-each>
					<metadataLastDateUpdated>2012-01-01</metadataLastDateUpdated>
					<xsl:for-each select="ns0:MetadataInfo/ns0:revision">
						<revision>
							<xsl:value-of select="string(.)"/>
						</revision>
					</xsl:for-each>
				</metadataInfo>
				<xsl:for-each select="ns0:VersionInfo">
					<versionInfo>
						<version>
							<xsl:value-of select="string(ns0:version)"/>
						</version>
						<xsl:for-each select="ns0:revision">
							<revision>
								<xsl:value-of select="string(.)"/>
							</revision>
						</xsl:for-each>
						<xsl:for-each select="ns0:lastDateUpdated">
							<lastDateUpdated>
								<xsl:value-of select="string(.)"/>
							</lastDateUpdated>
						</xsl:for-each>
						<xsl:for-each select="ns0:updateFrequency">
							<updateFrequency>
								<xsl:value-of select="string(.)"/>
							</updateFrequency>
						</xsl:for-each>
					</versionInfo>
				</xsl:for-each>
				<xsl:for-each select="ns0:ValidationInfo">
					<validationInfo>
						<validated>
							<xsl:value-of select="string((translate(string(ns0:validated), '1falseru0 ', 't') = 't'))"/>
						</validated>
						<xsl:for-each select="ns0:validationType">
							<validationType>
								<xsl:value-of select="string(.)"/>
							</validationType>
						</xsl:for-each>
						<xsl:for-each select="ns0:validationMode">
							<validationMode>
								<xsl:value-of select="string(.)"/>
							</validationMode>
						</xsl:for-each>
						<xsl:for-each select="ns0:validationModeDetails">
							<validationModeDetails>
								<xsl:value-of select="string(.)"/>
							</validationModeDetails>
						</xsl:for-each>
						<xsl:for-each select="ns0:validationExtent">
							<validationExtent>
								<xsl:value-of select="string(.)"/>
							</validationExtent>
						</xsl:for-each>
						<xsl:for-each select="ns0:validationExtentDetails">
							<validationExtentDetails>
								<xsl:value-of select="string(.)"/>
							</validationExtentDetails>
						</xsl:for-each>
						<xsl:for-each select="ns0:sizePerValidation">
							<sizePerValidation>
								<size>
									<xsl:value-of select="string(ns0:size)"/>
								</size>
								<sizeUnit>
									<xsl:value-of select="string(ns0:sizeUnit)"/>
								</sizeUnit>
							</sizePerValidation>
						</xsl:for-each>
						<xsl:for-each select="ns0:validationReport">
							<validationReport>
								<documentUnstructured>
									<xsl:value-of select="string(.)"/>
								</documentUnstructured>
							</validationReport>
						</xsl:for-each>
						<xsl:for-each select="ns0:validationTool">
							<validationTool>
								<xsl:value-of select="/.."/>
							</validationTool>
						</xsl:for-each>
						<xsl:for-each select="ns0:validator">
							<validator>
								<xsl:value-of select="/.."/>
							</validator>
						</xsl:for-each>
					</validationInfo>
				</xsl:for-each>
				<xsl:for-each select="ns0:UsageInfo">
					<usageInfo>
						<xsl:for-each select="ns0:accessTool">
							<accessTool>
								<xsl:value-of select="/.."/>
							</accessTool>
						</xsl:for-each>
					</usageInfo>
				</xsl:for-each>
				<xsl:for-each select="ns0:ResourceDocumentationInfo">
					<resourceDocumentationInfo>
						<xsl:for-each select="ns0:samplesLocation">
							<samplesLocation>
								<xsl:value-of select="string(.)"/>
							</samplesLocation>
						</xsl:for-each>
						<xsl:for-each select="ns0:toolDocumentationType">
							<toolDocumentationType>
								<xsl:value-of select="string(.)"/>
							</toolDocumentationType>
						</xsl:for-each>
					</resourceDocumentationInfo>
				</xsl:for-each>
				<xsl:for-each select="ns0:ResourceCreationInfo">
					<resourceCreationInfo>
						<xsl:for-each select="ns0:resourceCreator">
							<resourceCreator>
								<xsl:for-each select="ns0:PersonInfo">
									<personInfo>
										<xsl:for-each select="ns0:surname">
											<surname>
												<xsl:variable name="var28_lang">
													<xsl:if test="@ns0:lang">
														<xsl:value-of select="'1'"/>
													</xsl:if>
												</xsl:variable>
												<xsl:if test="string(boolean(string($var28_lang))) != 'false'">
													<xsl:attribute name="lang" namespace="">
														<xsl:value-of select="string(@ns0:lang)"/>
													</xsl:attribute>
												</xsl:if>
												<xsl:value-of select="string(.)"/>
											</surname>
										</xsl:for-each>
										<xsl:for-each select="ns0:givenName">
											<givenName>
												<xsl:variable name="var29_lang">
													<xsl:if test="@ns0:lang">
														<xsl:value-of select="'1'"/>
													</xsl:if>
												</xsl:variable>
												<xsl:if test="string(boolean(string($var29_lang))) != 'false'">
													<xsl:attribute name="lang" namespace="">
														<xsl:value-of select="string(@ns0:lang)"/>
													</xsl:attribute>
												</xsl:if>
												<xsl:value-of select="string(.)"/>
											</givenName>
										</xsl:for-each>
										<communicationInfo>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:email">
												<email>
													<xsl:value-of select="string(.)"/>
												</email>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:url">
												<url>
													<xsl:value-of select="string(.)"/>
												</url>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:address">
												<address>
													<xsl:value-of select="string(.)"/>
												</address>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:zipCode">
												<zipCode>
													<xsl:value-of select="string(.)"/>
												</zipCode>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:city">
												<city>
													<xsl:value-of select="string(.)"/>
												</city>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:country">
												<country>
													<xsl:value-of select="string(.)"/>
												</country>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:telephoneNumber">
												<telephoneNumber>
													<xsl:value-of select="string(.)"/>
												</telephoneNumber>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:faxNumber">
												<faxNumber>
													<xsl:value-of select="string(.)"/>
												</faxNumber>
											</xsl:for-each>
										</communicationInfo>
										<xsl:for-each select="ns0:position">
											<position>
												<xsl:value-of select="string(.)"/>
											</position>
										</xsl:for-each>
										<xsl:for-each select="ns0:affiliation">
											<affiliation>
												<organizationName>
													<xsl:variable name="var30_lang">
														<xsl:if test="ns0:OrganizationInfo/ns0:organizationName/@ns0:lang">
															<xsl:value-of select="'1'"/>
														</xsl:if>
													</xsl:variable>
													<xsl:if test="string(boolean(string($var30_lang))) != 'false'">
														<xsl:attribute name="lang" namespace="">
															<xsl:value-of select="string(ns0:OrganizationInfo/ns0:organizationName/@ns0:lang)"/>
														</xsl:attribute>
													</xsl:if>
													<xsl:value-of select="string(ns0:OrganizationInfo/ns0:organizationName)"/>
												</organizationName>
												<xsl:for-each select="ns0:OrganizationInfo/ns0:organizationShortName">
													<organizationShortName>
														<xsl:variable name="var31_lang">
															<xsl:if test="@ns0:lang">
																<xsl:value-of select="'1'"/>
															</xsl:if>
														</xsl:variable>
														<xsl:if test="string(boolean(string($var31_lang))) != 'false'">
															<xsl:attribute name="lang" namespace="">
																<xsl:value-of select="string(@ns0:lang)"/>
															</xsl:attribute>
														</xsl:if>
														<xsl:value-of select="string(.)"/>
													</organizationShortName>
												</xsl:for-each>
												<xsl:for-each select="ns0:OrganizationInfo/ns0:departmentName">
													<departmentName>
														<xsl:variable name="var32_lang">
															<xsl:if test="@ns0:lang">
																<xsl:value-of select="'1'"/>
															</xsl:if>
														</xsl:variable>
														<xsl:if test="string(boolean(string($var32_lang))) != 'false'">
															<xsl:attribute name="lang" namespace="">
																<xsl:value-of select="string(@ns0:lang)"/>
															</xsl:attribute>
														</xsl:if>
														<xsl:value-of select="string(.)"/>
													</departmentName>
												</xsl:for-each>
												<communicationInfo>
													<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:email">
														<email>
															<xsl:value-of select="string(.)"/>
														</email>
													</xsl:for-each>
													<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:url">
														<url>
															<xsl:value-of select="string(.)"/>
														</url>
													</xsl:for-each>
													<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:address">
														<address>
															<xsl:value-of select="string(.)"/>
														</address>
													</xsl:for-each>
													<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:zipCode">
														<zipCode>
															<xsl:value-of select="string(.)"/>
														</zipCode>
													</xsl:for-each>
													<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:city">
														<city>
															<xsl:value-of select="string(.)"/>
														</city>
													</xsl:for-each>
													<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:country">
														<country>
															<xsl:value-of select="string(.)"/>
														</country>
													</xsl:for-each>
													<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:telephoneNumber">
														<telephoneNumber>
															<xsl:value-of select="string(.)"/>
														</telephoneNumber>
													</xsl:for-each>
													<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:faxNumber">
														<faxNumber>
															<xsl:value-of select="string(.)"/>
														</faxNumber>
													</xsl:for-each>
												</communicationInfo>
											</affiliation>
										</xsl:for-each>
									</personInfo>
								</xsl:for-each>
								<xsl:for-each select="ns0:OrganizationInfo">
									<organizationInfo>
										<organizationName>
											<xsl:variable name="var33_lang">
												<xsl:if test="ns0:organizationName/@ns0:lang">
													<xsl:value-of select="'1'"/>
												</xsl:if>
											</xsl:variable>
											<xsl:if test="string(boolean(string($var33_lang))) != 'false'">
												<xsl:attribute name="lang" namespace="">
													<xsl:value-of select="string(ns0:organizationName/@ns0:lang)"/>
												</xsl:attribute>
											</xsl:if>
											<xsl:value-of select="string(ns0:organizationName)"/>
										</organizationName>
										<xsl:for-each select="ns0:organizationShortName">
											<organizationShortName>
												<xsl:variable name="var34_lang">
													<xsl:if test="@ns0:lang">
														<xsl:value-of select="'1'"/>
													</xsl:if>
												</xsl:variable>
												<xsl:if test="string(boolean(string($var34_lang))) != 'false'">
													<xsl:attribute name="lang" namespace="">
														<xsl:value-of select="string(@ns0:lang)"/>
													</xsl:attribute>
												</xsl:if>
												<xsl:value-of select="string(.)"/>
											</organizationShortName>
										</xsl:for-each>
										<xsl:for-each select="ns0:departmentName">
											<departmentName>
												<xsl:variable name="var35_lang">
													<xsl:if test="@ns0:lang">
														<xsl:value-of select="'1'"/>
													</xsl:if>
												</xsl:variable>
												<xsl:if test="string(boolean(string($var35_lang))) != 'false'">
													<xsl:attribute name="lang" namespace="">
														<xsl:value-of select="string(@ns0:lang)"/>
													</xsl:attribute>
												</xsl:if>
												<xsl:value-of select="string(.)"/>
											</departmentName>
										</xsl:for-each>
										<communicationInfo>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:email">
												<email>
													<xsl:value-of select="string(.)"/>
												</email>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:url">
												<url>
													<xsl:value-of select="string(.)"/>
												</url>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:address">
												<address>
													<xsl:value-of select="string(.)"/>
												</address>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:zipCode">
												<zipCode>
													<xsl:value-of select="string(.)"/>
												</zipCode>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:city">
												<city>
													<xsl:value-of select="string(.)"/>
												</city>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:country">
												<country>
													<xsl:value-of select="string(.)"/>
												</country>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:telephoneNumber">
												<telephoneNumber>
													<xsl:value-of select="string(.)"/>
												</telephoneNumber>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:faxNumber">
												<faxNumber>
													<xsl:value-of select="string(.)"/>
												</faxNumber>
											</xsl:for-each>
										</communicationInfo>
									</organizationInfo>
								</xsl:for-each>
							</resourceCreator>
						</xsl:for-each>
						<xsl:for-each select="ns0:creationStartDate">
							<creationStartDate>
								<xsl:value-of select="string(.)"/>
							</creationStartDate>
						</xsl:for-each>
						<xsl:for-each select="ns0:creationEndDate">
							<creationEndDate>
								<xsl:value-of select="string(.)"/>
							</creationEndDate>
						</xsl:for-each>
					</resourceCreationInfo>
				</xsl:for-each>
				<resourceComponentType>
					<lexicalConceptualResourceInfo>
						<resourceType>
							<xsl:value-of select="string(ns0:ContentInfo/ns0:resourceType)"/>
						</resourceType>
						<lexicalConceptualResourceType>
							<xsl:value-of select="string(ns0:LexicalConceptualResourceInfo/ns0:lexicalConceptualResourceType)"/>
						</lexicalConceptualResourceType>
						<xsl:for-each select="ns0:LexicalConceptualResourceInfo/ns0:LexicalConceptualResourceEncodingInfo">
							<lexicalConceptualResourceEncodingInfo>
								<xsl:for-each select="ns0:encodingLevel">
									<encodingLevel>
										<xsl:value-of select="string(.)"/>
									</encodingLevel>
								</xsl:for-each>
								<xsl:for-each select="ns0:linguisticInformation">
									<linguisticInformation>
										<xsl:value-of select="string(.)"/>
									</linguisticInformation>
								</xsl:for-each>
								<xsl:for-each select="ns0:theoreticModel">
									<theoreticModel>
										<xsl:value-of select="string(.)"/>
									</theoreticModel>
								</xsl:for-each>
								<xsl:for-each select="ns0:externalRef">
									<externalRef>
										<xsl:value-of select="string(.)"/>
									</externalRef>
								</xsl:for-each>
								<xsl:for-each select="ns0:extratextualInformation">
									<extratextualInformation>
										<xsl:value-of select="string(.)"/>
									</extratextualInformation>
								</xsl:for-each>
							</lexicalConceptualResourceEncodingInfo>
						</xsl:for-each>
						<xsl:for-each select="ns0:LexicalConceptualResourceInfo/ns0:LexicalConceptualResourceCreationInfo">
							<creationInfo>
								<xsl:for-each select="ns0:originalSource">
									<originalSource>
										<xsl:value-of select="/.."/>
									</originalSource>
								</xsl:for-each>
								<xsl:for-each select="ns0:creationMode">
									<creationMode>
										<xsl:value-of select="string(.)"/>
									</creationMode>
								</xsl:for-each>
								<xsl:for-each select="ns0:creationModeDetails">
									<creationModeDetails>
										<xsl:value-of select="string(.)"/>
									</creationModeDetails>
								</xsl:for-each>
								<xsl:for-each select="ns0:creationTool">
									<creationTool>
										<xsl:value-of select="/.."/>
									</creationTool>
								</xsl:for-each>
							</creationInfo>
						</xsl:for-each>
						<xsl:for-each select="ns0:TextInfo">
							<lexicalConceptualResourceMediaType>
								<lexicalConceptualResourceTextInfo>
									<mediaType>text</mediaType>
									<lingualityInfo>
										<lingualityType>
											<xsl:value-of select="string(ns0:LingualityInfo/ns0:lingualityType)"/>
										</lingualityType>
										<xsl:for-each select="ns0:LingualityInfo/ns0:multilingualityType">
											<multilingualityType>
												<xsl:value-of select="string(.)"/>
											</multilingualityType>
										</xsl:for-each>
										<xsl:for-each select="ns0:LingualityInfo/ns0:multilingualityTypeDetails">
											<multilingualityTypeDetails>
												<xsl:value-of select="string(.)"/>
											</multilingualityTypeDetails>
										</xsl:for-each>
									</lingualityInfo>
									<xsl:for-each select="ns0:LanguageInfo">
										<languageInfo>
											<languageId>
												<xsl:value-of select="string(ns0:languageId)"/>
											</languageId>
											<languageName>
												<xsl:value-of select="string(ns0:languageName)"/>
											</languageName>
											<xsl:for-each select="ns0:languageScript">
												<languageScript>
													<xsl:value-of select="string(.)"/>
												</languageScript>
											</xsl:for-each>
											<xsl:for-each select="ns0:sizePerLanguage">
												<sizePerLanguage>
													<size>
														<xsl:value-of select="string(ns0:size)"/>
													</size>
													<sizeUnit>
														<xsl:value-of select="string(ns0:sizeUnit)"/>
													</sizeUnit>
												</sizePerLanguage>
											</xsl:for-each>
										</languageInfo>
									</xsl:for-each>
									<xsl:for-each select="ns0:SizeInfo">
										<sizeInfo>
											<size>
												<xsl:value-of select="string(ns0:size)"/>
											</size>
											<sizeUnit>
												<xsl:value-of select="string(ns0:sizeUnit)"/>
											</sizeUnit>
										</sizeInfo>
									</xsl:for-each>
									<xsl:for-each select="ns0:CharacterEncodingInfo">
										<characterEncodingInfo>
											<xsl:for-each select="ns0:characterEncoding">
												<characterEncoding>
													<xsl:value-of select="string(.)"/>
												</characterEncoding>
											</xsl:for-each>
											<xsl:for-each select="ns0:sizePerCharacterEncoding">
												<sizePerCharacterEncoding>
													<size>
														<xsl:value-of select="string(ns0:size)"/>
													</size>
													<sizeUnit>
														<xsl:value-of select="string(ns0:sizeUnit)"/>
													</sizeUnit>
												</sizePerCharacterEncoding>
											</xsl:for-each>
										</characterEncodingInfo>
									</xsl:for-each>
									<xsl:for-each select="ns0:DomainInfo">
										<domainInfo>
											<domain>
												<xsl:value-of select="string(ns0:domain)"/>
											</domain>
											<xsl:for-each select="ns0:sizePerDomain">
												<sizePerDomain>
													<size>
														<xsl:value-of select="string(ns0:size)"/>
													</size>
													<sizeUnit>
														<xsl:value-of select="string(ns0:sizeUnit)"/>
													</sizeUnit>
												</sizePerDomain>
											</xsl:for-each>
										</domainInfo>
									</xsl:for-each>
									<xsl:for-each select="ns0:TimeCoverageInfo">
										<timeCoverageInfo>
											<timeCoverage>
												<xsl:value-of select="string(ns0:timeCoverage)"/>
											</timeCoverage>
											<xsl:for-each select="ns0:sizePerTimeCoverage">
												<sizePerTimeCoverage>
													<size>
														<xsl:value-of select="string(ns0:size)"/>
													</size>
													<sizeUnit>
														<xsl:value-of select="string(ns0:sizeUnit)"/>
													</sizeUnit>
												</sizePerTimeCoverage>
											</xsl:for-each>
										</timeCoverageInfo>
									</xsl:for-each>
									<xsl:for-each select="ns0:GeographicCoverageInfo">
										<geographicCoverageInfo>
											<geographicCoverage>
												<xsl:value-of select="string(ns0:geographicCoverage)"/>
											</geographicCoverage>
											<xsl:for-each select="ns0:sizePerGeographicCoverage">
												<sizePerGeographicCoverage>
													<size>
														<xsl:value-of select="string(ns0:size)"/>
													</size>
													<sizeUnit>
														<xsl:value-of select="string(ns0:sizeUnit)"/>
													</sizeUnit>
												</sizePerGeographicCoverage>
											</xsl:for-each>
										</geographicCoverageInfo>
									</xsl:for-each>
								</lexicalConceptualResourceTextInfo>
							</lexicalConceptualResourceMediaType>
						</xsl:for-each>
					</lexicalConceptualResourceInfo>
				</resourceComponentType>
			</xsl:for-each>
		</resourceInfo>
	</xsl:template>
</xsl:stylesheet>
