
SOLR_PORT=8983
SOLR_STOP_PORT=8079
SOLR_STOP_KEY=stopkey
SOLR_LOG=$SOLR_ROOT/solr.log
#DJANGO_PORT=9191
DJANGO_PORT=6789
PYTHON_PORT=9191
DJANGO_PID=$METASHARE_DIR/django.pid
LIGHTTPD_PID=$METASHARE_DIR/lighttpd.pid
DATABASE_FILE=$METASHARE_DIR/metashare.db
STORAGE_PATH=$METASHARE_DIR/storageFolder
LIGHT_CONF_FILE=$METASHARE_SW_DIR/misc/tools/ssl-config/lighttpd-ssl.conf

