# cfedermann: this should be moved somewhere else, as it does not belong to
#             the django object models directly.  It would also make sense to
#             check if using py-country would make things easier?
#             - http://pypi.python.org/pypi/pycountry
LANGUAGE_NAME_CHOICES = (
    'Bulgarian',
    'Bosnian',
    'Catalan; Valencian',
    'Croatian',
    'Basque',
    'Czech',
    'Danish',
    'German',
    'Ancient Greek (to 1453)',
    'Modern Greek (1453-)',
    'Greek Sign Language',
    'English',
    'Spanish',
    'Estonian',
    'Finnish',
    'French',
    'Irish',
    'Galician',
    'Welsh',
    'Hungarian',
    'Icelandic',
    'Italian',
    'Latvian',
    'Standard Latvian',
    'Lithuanian',
    'Maltese',
    'Dutch',
    'Norwegian',
    'Polish',
    'Portuguese',
    'Romanian',
    'Russian',
    'Serbian',
    'Slovak',
    'Slovenian',
    'Swedish',
    'Arabic',
    'Albanian',
    'Macedonian',
    'Turkish',
    'Chinese',
    'Persian',
    'Japanese',
    'Vietnamese',
    'Northern Sami',
)

LANGUAGE_NAME_CHOICES_3LET = (
    ('bul', 'Bulgarian'),
    ('bos', 'Bosnian'),
    ('cat', 'Catalan; Valencian'),
    ('ces', 'Czech'),
    ('hrv', 'Croatian'),
    ('eus', 'Basque'),
    ('dan', 'Danish'),
    ('deu', 'German'),
    ('grc',    'Ancient Greek (to 1453)'),
    ('ell', 'Modern Greek (1453-)'),
    ('gss', 'Greek Sign Language'),
    ('eng', 'English'),
    ('spa', 'Spanish'),
    ('est', 'Estonian'),
    ('fin', 'Finnish'),
    ('fra', 'French'),
    ('gle', 'Irish'),
    ('glg', 'Galician'),
    ('cym', 'Welsh'),
    ('hun', 'Hungarian'),
    ('isl', 'Icelandic'),
    ('ita', 'Italian'),
    ('lav', 'Latvian'),
    ('lvs', 'Standard Latvian'),
    ('lit', 'Lithuanian'),
    ('mlt', 'Maltese'),
    ('nld', 'Dutch'),
    ('nor', 'Norwegian'),
    ('pol', 'Polish'),
    ('por', 'Portuguese'),
    ('ron', 'Romanian'),
    ('rus', 'Russian'),
    ('srp', 'Serbian'),
    ('slk', 'Slovak'),
    ('slv', 'Slovenian'),
    ('swe', 'Swedish'),
    ('ara', 'Arabic'),
    ('sqi', 'Albanian'),
    ('mkd', 'Macedonian'),
    ('tur', 'Turkish'),
    ('zho', 'Chinese'),
    ('fas', 'Persian'),
    ('jpn', 'Japanese'),
    ('vie', 'Vietnamese'),
    ('sme', 'Northern Sami'),
)
