<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2012r2

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:agt="http://www.altova.com/Mapforce/agt" xmlns:ns0="http://www.ilsp.gr/META-XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="agt ns0 xs">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template name="agt:var6_MapToMETA-SHARE-Resource_function">
		<xsl:param name="par0"/>
		<email xmlns="http://www.ilsp.gr/META-XMLSchema">
			<xsl:value-of select="$par0"/>
		</email>
	</xsl:template>
	<xsl:template name="agt:var13_MapToMETA-SHARE-Resource_function">
		<xsl:param name="par0"/>
		<xsl:attribute name="lang">
			<xsl:value-of select="string($par0/@ns0:lang)"/>
		</xsl:attribute>
	</xsl:template>
	<xsl:template match="/">
		<resourceInfo xmlns="http://www.ilsp.gr/META-XMLSchema">
			<xsl:attribute name="xsi:schemaLocation" namespace="http://www.w3.org/2001/XMLSchema-instance">http://www.ilsp.gr/META-XMLSchema C:/develop/metashare/transform/schemaTransform/v2.0/META-SHARE-Resource.xsd</xsl:attribute>
			<xsl:for-each select="ns0:Resource">
				<xsl:variable name="var44_cur" select="."/>
				<identificationInfo>
					<resourceName>
						<xsl:variable name="var1_lang">
							<xsl:if test="ns0:IdentificationInfo/ns0:resourceName/@ns0:lang">
								<xsl:value-of select="'1'"/>
							</xsl:if>
						</xsl:variable>
						<xsl:if test="string(boolean(string($var1_lang))) != 'false'">
							<xsl:attribute name="lang" namespace="">
								<xsl:value-of select="string(ns0:IdentificationInfo/ns0:resourceName/@ns0:lang)"/>
							</xsl:attribute>
						</xsl:if>
						<xsl:value-of select="string(ns0:IdentificationInfo/ns0:resourceName)"/>
					</resourceName>
					<description>
						<xsl:value-of select="string(ns0:ContentInfo/ns0:description)"/>
					</description>
					<xsl:for-each select="ns0:IdentificationInfo/ns0:resourceShortName">
						<resourceShortName>
							<xsl:variable name="var2_lang">
								<xsl:if test="@ns0:lang">
									<xsl:value-of select="'1'"/>
								</xsl:if>
							</xsl:variable>
							<xsl:if test="string(boolean(string($var2_lang))) != 'false'">
								<xsl:attribute name="lang" namespace="">
									<xsl:value-of select="string(@ns0:lang)"/>
								</xsl:attribute>
							</xsl:if>
							<xsl:value-of select="string(.)"/>
						</resourceShortName>
					</xsl:for-each>
					<xsl:for-each select="ns0:IdentificationInfo/ns0:url">
						<url>
							<xsl:value-of select="string(.)"/>
						</url>
					</xsl:for-each>
					<metaShareId>
						<xsl:value-of select="string(ns0:IdentificationInfo/ns0:pid)"/>
					</metaShareId>
					<xsl:for-each select="ns0:IdentificationInfo/ns0:identifier">
						<identifier>
							<xsl:value-of select="string(.)"/>
						</identifier>
					</xsl:for-each>
				</identificationInfo>
				<distributionInfo>
					<availability>
						<xsl:value-of select="string(ns0:DistributionInfo/ns0:availability)"/>
					</availability>
					<xsl:for-each select="ns0:DistributionInfo/ns0:iprHolder">
						<iprHolder>
							<personInfo>
								<xsl:variable name="var4_resultof_map">
									<xsl:for-each select="ns0:PersonInfo">
										<xsl:variable name="var3_givenName">
											<xsl:if test="ns0:givenName">
												<xsl:value-of select="'1'"/>
											</xsl:if>
										</xsl:variable>
										<xsl:value-of select="boolean(string($var3_givenName))"/>
									</xsl:for-each>
								</xsl:variable>
								<givenName>
									<xsl:choose>
										<xsl:when test="string(boolean(translate(normalize-space($var4_resultof_map), 'false0 ', ''))) != 'false'">
											<xsl:value-of select="string(ns0:PersonInfo/ns0:givenName)"/>
										</xsl:when>
										<xsl:otherwise>
											<xsl:value-of select="'n/a'"/>
										</xsl:otherwise>
									</xsl:choose>
								</givenName>
								<communicationInfo>
									<xsl:variable name="var5_PersonInfo">
										<xsl:if test="ns0:PersonInfo">
											<xsl:value-of select="'1'"/>
										</xsl:if>
									</xsl:variable>
									<xsl:choose>
										<xsl:when test="string(boolean(string($var5_PersonInfo))) != 'false'">
											<xsl:for-each select="ns0:PersonInfo/ns0:CommunicationInfo/ns0:email">
												<xsl:call-template name="agt:var6_MapToMETA-SHARE-Resource_function">
													<xsl:with-param name="par0" select="string(.)"/>
												</xsl:call-template>
											</xsl:for-each>
										</xsl:when>
										<xsl:otherwise>
											<xsl:call-template name="agt:var6_MapToMETA-SHARE-Resource_function">
												<xsl:with-param name="par0" select="'dummy@example.com'"/>
											</xsl:call-template>
										</xsl:otherwise>
									</xsl:choose>
									<xsl:for-each select="ns0:PersonInfo/ns0:CommunicationInfo/ns0:url">
										<url>
											<xsl:value-of select="string(.)"/>
										</url>
									</xsl:for-each>
									<xsl:for-each select="ns0:PersonInfo/ns0:CommunicationInfo/ns0:address">
										<address>
											<xsl:value-of select="string(.)"/>
										</address>
									</xsl:for-each>
									<xsl:for-each select="ns0:PersonInfo/ns0:CommunicationInfo/ns0:zipCode">
										<zipCode>
											<xsl:value-of select="string(.)"/>
										</zipCode>
									</xsl:for-each>
									<xsl:for-each select="ns0:PersonInfo/ns0:CommunicationInfo/ns0:city">
										<city>
											<xsl:value-of select="string(.)"/>
										</city>
									</xsl:for-each>
									<xsl:for-each select="ns0:PersonInfo/ns0:CommunicationInfo/ns0:country">
										<country>
											<xsl:value-of select="string(.)"/>
										</country>
									</xsl:for-each>
									<xsl:for-each select="ns0:PersonInfo/ns0:CommunicationInfo/ns0:telephoneNumber">
										<telephoneNumber>
											<xsl:value-of select="string(.)"/>
										</telephoneNumber>
									</xsl:for-each>
									<xsl:for-each select="ns0:PersonInfo/ns0:CommunicationInfo/ns0:faxNumber">
										<faxNumber>
											<xsl:value-of select="string(.)"/>
										</faxNumber>
									</xsl:for-each>
								</communicationInfo>
								<xsl:for-each select="ns0:PersonInfo/ns0:position">
									<position>
										<xsl:value-of select="string(.)"/>
									</position>
								</xsl:for-each>
							</personInfo>
						</iprHolder>
					</xsl:for-each>
				</distributionInfo>
				<xsl:for-each select="ns0:contactPerson">
					<contactPerson>
						<xsl:for-each select="ns0:surname">
							<surname>
								<xsl:variable name="var7_lang">
									<xsl:if test="@ns0:lang">
										<xsl:value-of select="'1'"/>
									</xsl:if>
								</xsl:variable>
								<xsl:if test="string(boolean(string($var7_lang))) != 'false'">
									<xsl:attribute name="lang" namespace="">
										<xsl:value-of select="string(@ns0:lang)"/>
									</xsl:attribute>
								</xsl:if>
								<xsl:value-of select="string(.)"/>
							</surname>
						</xsl:for-each>
						<xsl:for-each select="ns0:givenName">
							<givenName>
								<xsl:variable name="var8_lang">
									<xsl:if test="@ns0:lang">
										<xsl:value-of select="'1'"/>
									</xsl:if>
								</xsl:variable>
								<xsl:if test="string(boolean(string($var8_lang))) != 'false'">
									<xsl:attribute name="lang" namespace="">
										<xsl:value-of select="string(@ns0:lang)"/>
									</xsl:attribute>
								</xsl:if>
								<xsl:value-of select="string(.)"/>
							</givenName>
						</xsl:for-each>
						<communicationInfo>
							<xsl:for-each select="ns0:CommunicationInfo/ns0:email">
								<email>
									<xsl:value-of select="string(.)"/>
								</email>
							</xsl:for-each>
							<xsl:for-each select="ns0:CommunicationInfo/ns0:url">
								<url>
									<xsl:value-of select="string(.)"/>
								</url>
							</xsl:for-each>
							<xsl:for-each select="ns0:CommunicationInfo/ns0:address">
								<address>
									<xsl:value-of select="string(.)"/>
								</address>
							</xsl:for-each>
							<xsl:for-each select="ns0:CommunicationInfo/ns0:zipCode">
								<zipCode>
									<xsl:value-of select="string(.)"/>
								</zipCode>
							</xsl:for-each>
							<xsl:for-each select="ns0:CommunicationInfo/ns0:city">
								<city>
									<xsl:value-of select="string(.)"/>
								</city>
							</xsl:for-each>
							<xsl:for-each select="ns0:CommunicationInfo/ns0:country">
								<country>
									<xsl:value-of select="string(.)"/>
								</country>
							</xsl:for-each>
							<xsl:for-each select="ns0:CommunicationInfo/ns0:telephoneNumber">
								<telephoneNumber>
									<xsl:value-of select="string(.)"/>
								</telephoneNumber>
							</xsl:for-each>
							<xsl:for-each select="ns0:CommunicationInfo/ns0:faxNumber">
								<faxNumber>
									<xsl:value-of select="string(.)"/>
								</faxNumber>
							</xsl:for-each>
						</communicationInfo>
						<xsl:for-each select="ns0:position">
							<position>
								<xsl:value-of select="string(.)"/>
							</position>
						</xsl:for-each>
						<xsl:for-each select="ns0:affiliation">
							<affiliation>
								<organizationName>
									<xsl:variable name="var9_lang">
										<xsl:if test="ns0:OrganizationInfo/ns0:organizationName/@ns0:lang">
											<xsl:value-of select="'1'"/>
										</xsl:if>
									</xsl:variable>
									<xsl:if test="string(boolean(string($var9_lang))) != 'false'">
										<xsl:attribute name="lang" namespace="">
											<xsl:value-of select="string(ns0:OrganizationInfo/ns0:organizationName/@ns0:lang)"/>
										</xsl:attribute>
									</xsl:if>
									<xsl:value-of select="string(ns0:OrganizationInfo/ns0:organizationName)"/>
								</organizationName>
								<xsl:for-each select="ns0:OrganizationInfo/ns0:organizationShortName">
									<organizationShortName>
										<xsl:variable name="var10_lang">
											<xsl:if test="@ns0:lang">
												<xsl:value-of select="'1'"/>
											</xsl:if>
										</xsl:variable>
										<xsl:if test="string(boolean(string($var10_lang))) != 'false'">
											<xsl:attribute name="lang" namespace="">
												<xsl:value-of select="string(@ns0:lang)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:value-of select="string(.)"/>
									</organizationShortName>
								</xsl:for-each>
								<xsl:for-each select="ns0:OrganizationInfo/ns0:departmentName">
									<departmentName>
										<xsl:variable name="var11_lang">
											<xsl:if test="@ns0:lang">
												<xsl:value-of select="'1'"/>
											</xsl:if>
										</xsl:variable>
										<xsl:if test="string(boolean(string($var11_lang))) != 'false'">
											<xsl:attribute name="lang" namespace="">
												<xsl:value-of select="string(@ns0:lang)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:value-of select="string(.)"/>
									</departmentName>
								</xsl:for-each>
								<communicationInfo>
									<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:email">
										<email>
											<xsl:value-of select="string(.)"/>
										</email>
									</xsl:for-each>
									<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:url">
										<url>
											<xsl:value-of select="string(.)"/>
										</url>
									</xsl:for-each>
									<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:address">
										<address>
											<xsl:value-of select="string(.)"/>
										</address>
									</xsl:for-each>
									<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:zipCode">
										<zipCode>
											<xsl:value-of select="string(.)"/>
										</zipCode>
									</xsl:for-each>
									<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:city">
										<city>
											<xsl:value-of select="string(.)"/>
										</city>
									</xsl:for-each>
									<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:country">
										<country>
											<xsl:value-of select="string(.)"/>
										</country>
									</xsl:for-each>
									<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:telephoneNumber">
										<telephoneNumber>
											<xsl:value-of select="string(.)"/>
										</telephoneNumber>
									</xsl:for-each>
									<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:faxNumber">
										<faxNumber>
											<xsl:value-of select="string(.)"/>
										</faxNumber>
									</xsl:for-each>
								</communicationInfo>
							</affiliation>
						</xsl:for-each>
					</contactPerson>
				</xsl:for-each>
				<metadataInfo>
					<metadataCreationDate>2012-01-30</metadataCreationDate>
					<xsl:for-each select="ns0:MetadataInfo/ns0:metadataCreator">
						<metadataCreator>
							<surname>
								<xsl:for-each select="ns0:surname">
									<xsl:variable name="var12_lang">
										<xsl:if test="@ns0:lang">
											<xsl:value-of select="'1'"/>
										</xsl:if>
									</xsl:variable>
									<xsl:if test="string(boolean(string($var12_lang))) != 'false'">
										<xsl:call-template name="agt:var13_MapToMETA-SHARE-Resource_function">
											<xsl:with-param name="par0" select="."/>
										</xsl:call-template>
									</xsl:if>
								</xsl:for-each>
								<xsl:variable name="var14_surname">
									<xsl:if test="ns0:surname">
										<xsl:value-of select="'1'"/>
									</xsl:if>
								</xsl:variable>
								<xsl:choose>
									<xsl:when test="string(boolean(string($var14_surname))) != 'false'">
										<xsl:value-of select="string(ns0:surname)"/>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="'n/a'"/>
									</xsl:otherwise>
								</xsl:choose>
							</surname>
							<xsl:variable name="var15_givenName">
								<xsl:if test="ns0:givenName">
									<xsl:value-of select="'1'"/>
								</xsl:if>
							</xsl:variable>
							<givenName>
								<xsl:choose>
									<xsl:when test="string(boolean(string($var15_givenName))) != 'false'">
										<xsl:value-of select="string(ns0:givenName)"/>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="'n/a'"/>
									</xsl:otherwise>
								</xsl:choose>
							</givenName>
							<communicationInfo>
								<xsl:for-each select="ns0:CommunicationInfo/ns0:email">
									<email>
										<xsl:value-of select="string(.)"/>
									</email>
								</xsl:for-each>
								<xsl:for-each select="ns0:CommunicationInfo/ns0:url">
									<url>
										<xsl:value-of select="string(.)"/>
									</url>
								</xsl:for-each>
								<xsl:for-each select="ns0:CommunicationInfo/ns0:address">
									<address>
										<xsl:value-of select="string(.)"/>
									</address>
								</xsl:for-each>
								<xsl:for-each select="ns0:CommunicationInfo/ns0:zipCode">
									<zipCode>
										<xsl:value-of select="string(.)"/>
									</zipCode>
								</xsl:for-each>
								<xsl:for-each select="ns0:CommunicationInfo/ns0:city">
									<city>
										<xsl:value-of select="string(.)"/>
									</city>
								</xsl:for-each>
								<xsl:for-each select="ns0:CommunicationInfo/ns0:country">
									<country>
										<xsl:value-of select="string(.)"/>
									</country>
								</xsl:for-each>
								<xsl:for-each select="ns0:CommunicationInfo/ns0:telephoneNumber">
									<telephoneNumber>
										<xsl:value-of select="string(.)"/>
									</telephoneNumber>
								</xsl:for-each>
								<xsl:for-each select="ns0:CommunicationInfo/ns0:faxNumber">
									<faxNumber>
										<xsl:value-of select="string(.)"/>
									</faxNumber>
								</xsl:for-each>
							</communicationInfo>
							<xsl:for-each select="ns0:position">
								<position>
									<xsl:value-of select="string(.)"/>
								</position>
							</xsl:for-each>
							<xsl:for-each select="ns0:affiliation">
								<affiliation>
									<organizationName>
										<xsl:variable name="var16_lang">
											<xsl:if test="ns0:OrganizationInfo/ns0:organizationName/@ns0:lang">
												<xsl:value-of select="'1'"/>
											</xsl:if>
										</xsl:variable>
										<xsl:if test="string(boolean(string($var16_lang))) != 'false'">
											<xsl:attribute name="lang" namespace="">
												<xsl:value-of select="string(ns0:OrganizationInfo/ns0:organizationName/@ns0:lang)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:value-of select="string(ns0:OrganizationInfo/ns0:organizationName)"/>
									</organizationName>
									<xsl:for-each select="ns0:OrganizationInfo/ns0:organizationShortName">
										<organizationShortName>
											<xsl:variable name="var17_lang">
												<xsl:if test="@ns0:lang">
													<xsl:value-of select="'1'"/>
												</xsl:if>
											</xsl:variable>
											<xsl:if test="string(boolean(string($var17_lang))) != 'false'">
												<xsl:attribute name="lang" namespace="">
													<xsl:value-of select="string(@ns0:lang)"/>
												</xsl:attribute>
											</xsl:if>
											<xsl:value-of select="string(.)"/>
										</organizationShortName>
									</xsl:for-each>
									<xsl:for-each select="ns0:OrganizationInfo/ns0:departmentName">
										<departmentName>
											<xsl:variable name="var18_lang">
												<xsl:if test="@ns0:lang">
													<xsl:value-of select="'1'"/>
												</xsl:if>
											</xsl:variable>
											<xsl:if test="string(boolean(string($var18_lang))) != 'false'">
												<xsl:attribute name="lang" namespace="">
													<xsl:value-of select="string(@ns0:lang)"/>
												</xsl:attribute>
											</xsl:if>
											<xsl:value-of select="string(.)"/>
										</departmentName>
									</xsl:for-each>
									<communicationInfo>
										<xsl:variable name="var19_resultof_map">
											<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:email">
												<xsl:value-of select="string(.)"/>
											</xsl:for-each>
										</xsl:variable>
										<email>
											<xsl:choose>
												<xsl:when test="string((string(false()) = 'true')) != 'false'">
													<xsl:value-of select="'tobe@replaced.mail'"/>
												</xsl:when>
												<xsl:otherwise>
													<xsl:value-of select="$var19_resultof_map"/>
												</xsl:otherwise>
											</xsl:choose>
										</email>
										<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:email">
											<email>
												<xsl:choose>
													<xsl:when test="string((string(.) = '')) != 'false'">
														<xsl:value-of select="'tobe@replaced.mail'"/>
													</xsl:when>
													<xsl:otherwise>
														<xsl:value-of select="string(.)"/>
													</xsl:otherwise>
												</xsl:choose>
											</email>
										</xsl:for-each>
										<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:url">
											<url>
												<xsl:value-of select="string(.)"/>
											</url>
										</xsl:for-each>
										<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:address">
											<address>
												<xsl:value-of select="string(.)"/>
											</address>
										</xsl:for-each>
										<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:zipCode">
											<zipCode>
												<xsl:value-of select="string(.)"/>
											</zipCode>
										</xsl:for-each>
										<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:city">
											<city>
												<xsl:value-of select="string(.)"/>
											</city>
										</xsl:for-each>
										<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:country">
											<country>
												<xsl:value-of select="string(.)"/>
											</country>
										</xsl:for-each>
										<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:telephoneNumber">
											<telephoneNumber>
												<xsl:value-of select="string(.)"/>
											</telephoneNumber>
										</xsl:for-each>
										<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:faxNumber">
											<faxNumber>
												<xsl:value-of select="string(.)"/>
											</faxNumber>
										</xsl:for-each>
									</communicationInfo>
								</affiliation>
							</xsl:for-each>
						</metadataCreator>
					</xsl:for-each>
					<xsl:for-each select="ns0:MetadataInfo/ns0:source">
						<source>
							<xsl:value-of select="string(.)"/>
						</source>
					</xsl:for-each>
					<xsl:for-each select="ns0:MetadataInfo/ns0:originalMetadataSchema">
						<originalMetadataSchema>
							<xsl:value-of select="string(.)"/>
						</originalMetadataSchema>
					</xsl:for-each>
					<xsl:for-each select="ns0:MetadataInfo/ns0:originalMetadataLink">
						<originalMetadataLink>
							<xsl:value-of select="string(.)"/>
						</originalMetadataLink>
					</xsl:for-each>
					<xsl:for-each select="ns0:MetadataInfo/ns0:metadataLastDateUpdated">
						<metadataLastDateUpdated>
							<xsl:value-of select="string(.)"/>
						</metadataLastDateUpdated>
					</xsl:for-each>
					<xsl:for-each select="ns0:MetadataInfo/ns0:revision">
						<revision>
							<xsl:value-of select="string(.)"/>
						</revision>
					</xsl:for-each>
				</metadataInfo>
				<xsl:for-each select="ns0:VersionInfo">
					<versionInfo>
						<version>
							<xsl:value-of select="string(ns0:version)"/>
						</version>
						<xsl:for-each select="ns0:revision">
							<revision>
								<xsl:value-of select="string(.)"/>
							</revision>
						</xsl:for-each>
						<xsl:for-each select="ns0:lastDateUpdated">
							<lastDateUpdated>
								<xsl:value-of select="string(.)"/>
							</lastDateUpdated>
						</xsl:for-each>
						<xsl:for-each select="ns0:updateFrequency">
							<updateFrequency>
								<xsl:value-of select="string(.)"/>
							</updateFrequency>
						</xsl:for-each>
					</versionInfo>
				</xsl:for-each>
				<xsl:for-each select="ns0:ValidationInfo">
					<validationInfo>
						<validated>
							<xsl:value-of select="string((translate(string(ns0:validated), '1falseru0 ', 't') = 't'))"/>
						</validated>
						<xsl:for-each select="ns0:validationType">
							<validationType>
								<xsl:value-of select="string(.)"/>
							</validationType>
						</xsl:for-each>
						<xsl:for-each select="ns0:validationMode">
							<validationMode>
								<xsl:value-of select="string(.)"/>
							</validationMode>
						</xsl:for-each>
						<xsl:for-each select="ns0:validationModeDetails">
							<validationModeDetails>
								<xsl:value-of select="string(.)"/>
							</validationModeDetails>
						</xsl:for-each>
						<xsl:for-each select="ns0:validationExtent">
							<validationExtent>
								<xsl:value-of select="string(.)"/>
							</validationExtent>
						</xsl:for-each>
						<xsl:for-each select="ns0:validationExtentDetails">
							<validationExtentDetails>
								<xsl:value-of select="string(.)"/>
							</validationExtentDetails>
						</xsl:for-each>
						<xsl:for-each select="ns0:sizePerValidation">
							<sizePerValidation>
								<size>
									<xsl:value-of select="string(ns0:size)"/>
								</size>
								<sizeUnit>
									<xsl:value-of select="string(ns0:sizeUnit)"/>
								</sizeUnit>
							</sizePerValidation>
						</xsl:for-each>
						<xsl:for-each select="ns0:validationReport">
							<validationReport>
								<documentUnstructured>
									<xsl:value-of select="string(.)"/>
								</documentUnstructured>
							</validationReport>
						</xsl:for-each>
						<validationTool>
							<xsl:for-each select="ns0:validationTool">
								<targetResourceNameURI>
									<xsl:value-of select="string(.)"/>
								</targetResourceNameURI>
							</xsl:for-each>
						</validationTool>
						<xsl:for-each select="ns0:validator">
							<validator>
								<xsl:for-each select="ns0:PersonInfo">
									<personInfo>
										<xsl:for-each select="ns0:surname">
											<surname>
												<xsl:variable name="var20_lang">
													<xsl:if test="@ns0:lang">
														<xsl:value-of select="'1'"/>
													</xsl:if>
												</xsl:variable>
												<xsl:if test="string(boolean(string($var20_lang))) != 'false'">
													<xsl:attribute name="lang" namespace="">
														<xsl:value-of select="string(@ns0:lang)"/>
													</xsl:attribute>
												</xsl:if>
												<xsl:value-of select="string(.)"/>
											</surname>
										</xsl:for-each>
										<xsl:for-each select="ns0:givenName">
											<givenName>
												<xsl:variable name="var21_lang">
													<xsl:if test="@ns0:lang">
														<xsl:value-of select="'1'"/>
													</xsl:if>
												</xsl:variable>
												<xsl:if test="string(boolean(string($var21_lang))) != 'false'">
													<xsl:attribute name="lang" namespace="">
														<xsl:value-of select="string(@ns0:lang)"/>
													</xsl:attribute>
												</xsl:if>
												<xsl:value-of select="string(.)"/>
											</givenName>
										</xsl:for-each>
										<communicationInfo>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:email">
												<email>
													<xsl:value-of select="string(.)"/>
												</email>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:url">
												<url>
													<xsl:value-of select="string(.)"/>
												</url>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:address">
												<address>
													<xsl:value-of select="string(.)"/>
												</address>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:zipCode">
												<zipCode>
													<xsl:value-of select="string(.)"/>
												</zipCode>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:city">
												<city>
													<xsl:value-of select="string(.)"/>
												</city>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:country">
												<country>
													<xsl:value-of select="string(.)"/>
												</country>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:telephoneNumber">
												<telephoneNumber>
													<xsl:value-of select="string(.)"/>
												</telephoneNumber>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:faxNumber">
												<faxNumber>
													<xsl:value-of select="string(.)"/>
												</faxNumber>
											</xsl:for-each>
										</communicationInfo>
										<xsl:for-each select="ns0:position">
											<position>
												<xsl:value-of select="string(.)"/>
											</position>
										</xsl:for-each>
										<xsl:for-each select="ns0:affiliation">
											<affiliation>
												<organizationName>
													<xsl:variable name="var22_lang">
														<xsl:if test="ns0:OrganizationInfo/ns0:organizationName/@ns0:lang">
															<xsl:value-of select="'1'"/>
														</xsl:if>
													</xsl:variable>
													<xsl:if test="string(boolean(string($var22_lang))) != 'false'">
														<xsl:attribute name="lang" namespace="">
															<xsl:value-of select="string(ns0:OrganizationInfo/ns0:organizationName/@ns0:lang)"/>
														</xsl:attribute>
													</xsl:if>
													<xsl:value-of select="string(ns0:OrganizationInfo/ns0:organizationName)"/>
												</organizationName>
												<xsl:for-each select="ns0:OrganizationInfo/ns0:organizationShortName">
													<organizationShortName>
														<xsl:variable name="var23_lang">
															<xsl:if test="@ns0:lang">
																<xsl:value-of select="'1'"/>
															</xsl:if>
														</xsl:variable>
														<xsl:if test="string(boolean(string($var23_lang))) != 'false'">
															<xsl:attribute name="lang" namespace="">
																<xsl:value-of select="string(@ns0:lang)"/>
															</xsl:attribute>
														</xsl:if>
														<xsl:value-of select="string(.)"/>
													</organizationShortName>
												</xsl:for-each>
												<xsl:for-each select="ns0:OrganizationInfo/ns0:departmentName">
													<departmentName>
														<xsl:variable name="var24_lang">
															<xsl:if test="@ns0:lang">
																<xsl:value-of select="'1'"/>
															</xsl:if>
														</xsl:variable>
														<xsl:if test="string(boolean(string($var24_lang))) != 'false'">
															<xsl:attribute name="lang" namespace="">
																<xsl:value-of select="string(@ns0:lang)"/>
															</xsl:attribute>
														</xsl:if>
														<xsl:value-of select="string(.)"/>
													</departmentName>
												</xsl:for-each>
												<communicationInfo>
													<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:email">
														<email>
															<xsl:value-of select="string(.)"/>
														</email>
													</xsl:for-each>
													<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:url">
														<url>
															<xsl:value-of select="string(.)"/>
														</url>
													</xsl:for-each>
													<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:address">
														<address>
															<xsl:value-of select="string(.)"/>
														</address>
													</xsl:for-each>
													<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:zipCode">
														<zipCode>
															<xsl:value-of select="string(.)"/>
														</zipCode>
													</xsl:for-each>
													<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:city">
														<city>
															<xsl:value-of select="string(.)"/>
														</city>
													</xsl:for-each>
													<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:country">
														<country>
															<xsl:value-of select="string(.)"/>
														</country>
													</xsl:for-each>
													<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:telephoneNumber">
														<telephoneNumber>
															<xsl:value-of select="string(.)"/>
														</telephoneNumber>
													</xsl:for-each>
													<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:faxNumber">
														<faxNumber>
															<xsl:value-of select="string(.)"/>
														</faxNumber>
													</xsl:for-each>
												</communicationInfo>
											</affiliation>
										</xsl:for-each>
									</personInfo>
								</xsl:for-each>
								<xsl:for-each select="ns0:OrganizationInfo">
									<organizationInfo>
										<organizationName>
											<xsl:variable name="var25_lang">
												<xsl:if test="ns0:organizationName/@ns0:lang">
													<xsl:value-of select="'1'"/>
												</xsl:if>
											</xsl:variable>
											<xsl:if test="string(boolean(string($var25_lang))) != 'false'">
												<xsl:attribute name="lang" namespace="">
													<xsl:value-of select="string(ns0:organizationName/@ns0:lang)"/>
												</xsl:attribute>
											</xsl:if>
											<xsl:value-of select="string(ns0:organizationName)"/>
										</organizationName>
										<xsl:for-each select="ns0:organizationShortName">
											<organizationShortName>
												<xsl:variable name="var26_lang">
													<xsl:if test="@ns0:lang">
														<xsl:value-of select="'1'"/>
													</xsl:if>
												</xsl:variable>
												<xsl:if test="string(boolean(string($var26_lang))) != 'false'">
													<xsl:attribute name="lang" namespace="">
														<xsl:value-of select="string(@ns0:lang)"/>
													</xsl:attribute>
												</xsl:if>
												<xsl:value-of select="string(.)"/>
											</organizationShortName>
										</xsl:for-each>
										<xsl:for-each select="ns0:departmentName">
											<departmentName>
												<xsl:variable name="var27_lang">
													<xsl:if test="@ns0:lang">
														<xsl:value-of select="'1'"/>
													</xsl:if>
												</xsl:variable>
												<xsl:if test="string(boolean(string($var27_lang))) != 'false'">
													<xsl:attribute name="lang" namespace="">
														<xsl:value-of select="string(@ns0:lang)"/>
													</xsl:attribute>
												</xsl:if>
												<xsl:value-of select="string(.)"/>
											</departmentName>
										</xsl:for-each>
									</organizationInfo>
								</xsl:for-each>
							</validator>
						</xsl:for-each>
					</validationInfo>
				</xsl:for-each>
				<xsl:for-each select="ns0:UsageInfo">
					<usageInfo>
						<xsl:for-each select="ns0:accessTool">
							<accessTool>
								<targetResourceNameURI>
									<xsl:value-of select="string(.)"/>
								</targetResourceNameURI>
							</accessTool>
						</xsl:for-each>
					</usageInfo>
				</xsl:for-each>
				<xsl:for-each select="ns0:ResourceDocumentationInfo">
					<resourceDocumentationInfo>
						<xsl:for-each select="ns0:samplesLocation">
							<samplesLocation>
								<xsl:value-of select="string(.)"/>
							</samplesLocation>
						</xsl:for-each>
						<xsl:for-each select="ns0:toolDocumentationType">
							<toolDocumentationType>
								<xsl:value-of select="string(.)"/>
							</toolDocumentationType>
						</xsl:for-each>
					</resourceDocumentationInfo>
				</xsl:for-each>
				<xsl:for-each select="ns0:ResourceCreationInfo">
					<resourceCreationInfo>
						<xsl:for-each select="ns0:resourceCreator">
							<resourceCreator>
								<xsl:for-each select="ns0:PersonInfo">
									<xsl:variable name="var33_cur" select="."/>
									<personInfo>
										<xsl:for-each select="ns0:surname">
											<surname>
												<xsl:variable name="var28_lang">
													<xsl:if test="@ns0:lang">
														<xsl:value-of select="'1'"/>
													</xsl:if>
												</xsl:variable>
												<xsl:if test="string(boolean(string($var28_lang))) != 'false'">
													<xsl:attribute name="lang" namespace="">
														<xsl:value-of select="string(@ns0:lang)"/>
													</xsl:attribute>
												</xsl:if>
												<xsl:value-of select="string(.)"/>
											</surname>
										</xsl:for-each>
										<xsl:for-each select="ns0:givenName">
											<givenName>
												<xsl:variable name="var29_lang">
													<xsl:if test="@ns0:lang">
														<xsl:value-of select="'1'"/>
													</xsl:if>
												</xsl:variable>
												<xsl:if test="string(boolean(string($var29_lang))) != 'false'">
													<xsl:attribute name="lang" namespace="">
														<xsl:value-of select="string(@ns0:lang)"/>
													</xsl:attribute>
												</xsl:if>
												<xsl:value-of select="string(.)"/>
											</givenName>
										</xsl:for-each>
										<xsl:for-each select="ns0:affiliation">
											<communicationInfo>
												<xsl:for-each select="$var33_cur/ns0:CommunicationInfo/ns0:email">
													<email>
														<xsl:value-of select="string(.)"/>
													</email>
												</xsl:for-each>
												<xsl:for-each select="$var33_cur/ns0:CommunicationInfo/ns0:url">
													<url>
														<xsl:value-of select="string(.)"/>
													</url>
												</xsl:for-each>
												<xsl:for-each select="$var33_cur/ns0:CommunicationInfo/ns0:address">
													<address>
														<xsl:value-of select="string(.)"/>
													</address>
												</xsl:for-each>
												<xsl:for-each select="$var33_cur/ns0:CommunicationInfo/ns0:zipCode">
													<zipCode>
														<xsl:value-of select="string(.)"/>
													</zipCode>
												</xsl:for-each>
												<xsl:for-each select="$var33_cur/ns0:CommunicationInfo/ns0:city">
													<city>
														<xsl:value-of select="string(.)"/>
													</city>
												</xsl:for-each>
												<xsl:for-each select="$var33_cur/ns0:CommunicationInfo/ns0:country">
													<country>
														<xsl:value-of select="string(.)"/>
													</country>
												</xsl:for-each>
												<xsl:for-each select="$var33_cur/ns0:CommunicationInfo/ns0:telephoneNumber">
													<telephoneNumber>
														<xsl:value-of select="string(.)"/>
													</telephoneNumber>
												</xsl:for-each>
												<xsl:for-each select="$var33_cur/ns0:CommunicationInfo/ns0:faxNumber">
													<faxNumber>
														<xsl:value-of select="string(.)"/>
													</faxNumber>
												</xsl:for-each>
											</communicationInfo>
										</xsl:for-each>
										<xsl:for-each select="ns0:position">
											<position>
												<xsl:value-of select="string(.)"/>
											</position>
										</xsl:for-each>
										<xsl:for-each select="ns0:affiliation">
											<affiliation>
												<organizationName>
													<xsl:variable name="var30_lang">
														<xsl:if test="ns0:OrganizationInfo/ns0:organizationName/@ns0:lang">
															<xsl:value-of select="'1'"/>
														</xsl:if>
													</xsl:variable>
													<xsl:if test="string(boolean(string($var30_lang))) != 'false'">
														<xsl:attribute name="lang" namespace="">
															<xsl:value-of select="string(ns0:OrganizationInfo/ns0:organizationName/@ns0:lang)"/>
														</xsl:attribute>
													</xsl:if>
													<xsl:value-of select="string(ns0:OrganizationInfo/ns0:organizationName)"/>
												</organizationName>
												<xsl:for-each select="ns0:OrganizationInfo/ns0:organizationShortName">
													<organizationShortName>
														<xsl:variable name="var31_lang">
															<xsl:if test="@ns0:lang">
																<xsl:value-of select="'1'"/>
															</xsl:if>
														</xsl:variable>
														<xsl:if test="string(boolean(string($var31_lang))) != 'false'">
															<xsl:attribute name="lang" namespace="">
																<xsl:value-of select="string(@ns0:lang)"/>
															</xsl:attribute>
														</xsl:if>
														<xsl:value-of select="string(.)"/>
													</organizationShortName>
												</xsl:for-each>
												<xsl:for-each select="ns0:OrganizationInfo/ns0:departmentName">
													<departmentName>
														<xsl:variable name="var32_lang">
															<xsl:if test="@ns0:lang">
																<xsl:value-of select="'1'"/>
															</xsl:if>
														</xsl:variable>
														<xsl:if test="string(boolean(string($var32_lang))) != 'false'">
															<xsl:attribute name="lang" namespace="">
																<xsl:value-of select="string(@ns0:lang)"/>
															</xsl:attribute>
														</xsl:if>
														<xsl:value-of select="string(.)"/>
													</departmentName>
												</xsl:for-each>
												<communicationInfo>
													<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:email">
														<email>
															<xsl:value-of select="string(.)"/>
														</email>
													</xsl:for-each>
													<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:url">
														<url>
															<xsl:value-of select="string(.)"/>
														</url>
													</xsl:for-each>
													<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:address">
														<address>
															<xsl:value-of select="string(.)"/>
														</address>
													</xsl:for-each>
													<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:zipCode">
														<zipCode>
															<xsl:value-of select="string(.)"/>
														</zipCode>
													</xsl:for-each>
													<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:city">
														<city>
															<xsl:value-of select="string(.)"/>
														</city>
													</xsl:for-each>
													<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:country">
														<country>
															<xsl:value-of select="string(.)"/>
														</country>
													</xsl:for-each>
													<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:telephoneNumber">
														<telephoneNumber>
															<xsl:value-of select="string(.)"/>
														</telephoneNumber>
													</xsl:for-each>
													<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:faxNumber">
														<faxNumber>
															<xsl:value-of select="string(.)"/>
														</faxNumber>
													</xsl:for-each>
												</communicationInfo>
											</affiliation>
										</xsl:for-each>
									</personInfo>
								</xsl:for-each>
								<xsl:for-each select="ns0:OrganizationInfo">
									<organizationInfo>
										<organizationName>
											<xsl:variable name="var34_lang">
												<xsl:if test="ns0:organizationName/@ns0:lang">
													<xsl:value-of select="'1'"/>
												</xsl:if>
											</xsl:variable>
											<xsl:if test="string(boolean(string($var34_lang))) != 'false'">
												<xsl:attribute name="lang" namespace="">
													<xsl:value-of select="string(ns0:organizationName/@ns0:lang)"/>
												</xsl:attribute>
											</xsl:if>
											<xsl:value-of select="string(ns0:organizationName)"/>
										</organizationName>
										<xsl:for-each select="ns0:organizationShortName">
											<organizationShortName>
												<xsl:variable name="var35_lang">
													<xsl:if test="@ns0:lang">
														<xsl:value-of select="'1'"/>
													</xsl:if>
												</xsl:variable>
												<xsl:if test="string(boolean(string($var35_lang))) != 'false'">
													<xsl:attribute name="lang" namespace="">
														<xsl:value-of select="string(@ns0:lang)"/>
													</xsl:attribute>
												</xsl:if>
												<xsl:value-of select="string(.)"/>
											</organizationShortName>
										</xsl:for-each>
										<xsl:for-each select="ns0:departmentName">
											<departmentName>
												<xsl:variable name="var36_lang">
													<xsl:if test="@ns0:lang">
														<xsl:value-of select="'1'"/>
													</xsl:if>
												</xsl:variable>
												<xsl:if test="string(boolean(string($var36_lang))) != 'false'">
													<xsl:attribute name="lang" namespace="">
														<xsl:value-of select="string(@ns0:lang)"/>
													</xsl:attribute>
												</xsl:if>
												<xsl:value-of select="string(.)"/>
											</departmentName>
										</xsl:for-each>
										<communicationInfo>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:address">
												<email>
													<xsl:value-of select="string(.)"/>
												</email>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:url">
												<url>
													<xsl:value-of select="string(.)"/>
												</url>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:address">
												<address>
													<xsl:value-of select="string(.)"/>
												</address>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:zipCode">
												<zipCode>
													<xsl:value-of select="string(.)"/>
												</zipCode>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:city">
												<city>
													<xsl:value-of select="string(.)"/>
												</city>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:country">
												<country>
													<xsl:value-of select="string(.)"/>
												</country>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:telephoneNumber">
												<telephoneNumber>
													<xsl:value-of select="string(.)"/>
												</telephoneNumber>
											</xsl:for-each>
											<xsl:for-each select="ns0:CommunicationInfo/ns0:faxNumber">
												<faxNumber>
													<xsl:value-of select="string(.)"/>
												</faxNumber>
											</xsl:for-each>
										</communicationInfo>
									</organizationInfo>
								</xsl:for-each>
							</resourceCreator>
						</xsl:for-each>
						<xsl:for-each select="ns0:FundingInfo/ns0:ProjectInfo">
							<fundingProject>
								<projectName>
									<xsl:variable name="var37_lang">
										<xsl:if test="ns0:projectName/@ns0:lang">
											<xsl:value-of select="'1'"/>
										</xsl:if>
									</xsl:variable>
									<xsl:if test="string(boolean(string($var37_lang))) != 'false'">
										<xsl:attribute name="lang" namespace="">
											<xsl:value-of select="string(ns0:projectName/@ns0:lang)"/>
										</xsl:attribute>
									</xsl:if>
									<xsl:value-of select="string(ns0:projectName)"/>
								</projectName>
								<xsl:for-each select="ns0:projectShortName">
									<projectShortName>
										<xsl:variable name="var38_lang">
											<xsl:if test="@ns0:lang">
												<xsl:value-of select="'1'"/>
											</xsl:if>
										</xsl:variable>
										<xsl:if test="string(boolean(string($var38_lang))) != 'false'">
											<xsl:attribute name="lang" namespace="">
												<xsl:value-of select="string(@ns0:lang)"/>
											</xsl:attribute>
										</xsl:if>
										<xsl:value-of select="string(.)"/>
									</projectShortName>
								</xsl:for-each>
								<xsl:for-each select="ns0:projectID">
									<projectID>
										<xsl:value-of select="string(.)"/>
									</projectID>
								</xsl:for-each>
								<xsl:for-each select="ns0:url">
									<url>
										<xsl:value-of select="string(.)"/>
									</url>
								</xsl:for-each>
								<xsl:for-each select="ns0:fundingType">
									<fundingType>
										<xsl:value-of select="string(.)"/>
									</fundingType>
								</xsl:for-each>
								<xsl:for-each select="ns0:funder">
									<funder>
										<xsl:value-of select="string(.)"/>
									</funder>
								</xsl:for-each>
								<xsl:for-each select="ns0:fundingCountry">
									<fundingCountry>
										<xsl:value-of select="string(.)"/>
									</fundingCountry>
								</xsl:for-each>
								<xsl:for-each select="ns0:projectStartDate">
									<projectStartDate>
										<xsl:value-of select="string(.)"/>
									</projectStartDate>
								</xsl:for-each>
								<xsl:for-each select="ns0:projectEndDate">
									<projectEndDate>
										<xsl:value-of select="string(.)"/>
									</projectEndDate>
								</xsl:for-each>
							</fundingProject>
						</xsl:for-each>
						<xsl:for-each select="ns0:creationStartDate">
							<creationStartDate>
								<xsl:value-of select="string(.)"/>
							</creationStartDate>
						</xsl:for-each>
						<xsl:for-each select="ns0:creationEndDate">
							<creationEndDate>
								<xsl:value-of select="string(.)"/>
							</creationEndDate>
						</xsl:for-each>
					</resourceCreationInfo>
				</xsl:for-each>
				<resourceComponentType>
					<corpusInfo>
						<resourceType>
							<xsl:value-of select="string(ns0:ContentInfo/ns0:resourceType)"/>
						</resourceType>
						<corpusMediaType>
							<xsl:for-each select="ns0:TextInfo">
								<corpusTextInfo>
									<xsl:for-each select="$var44_cur/ns0:ContentInfo/ns0:mediaType">
										<mediaType>
											<xsl:value-of select="string(.)"/>
										</mediaType>
									</xsl:for-each>
									<lingualityInfo>
										<lingualityType>
											<xsl:value-of select="string(ns0:LingualityInfo/ns0:lingualityType)"/>
										</lingualityType>
										<xsl:for-each select="ns0:LingualityInfo/ns0:multilingualityType">
											<multilingualityType>
												<xsl:value-of select="string(.)"/>
											</multilingualityType>
										</xsl:for-each>
										<xsl:for-each select="ns0:LingualityInfo/ns0:multilingualityTypeDetails">
											<multilingualityTypeDetails>
												<xsl:value-of select="string(.)"/>
											</multilingualityTypeDetails>
										</xsl:for-each>
									</lingualityInfo>
									<xsl:for-each select="ns0:LanguageInfo">
										<languageInfo>
											<languageId>
												<xsl:value-of select="string(ns0:languageId)"/>
											</languageId>
											<languageName>
												<xsl:value-of select="string(ns0:languageName)"/>
											</languageName>
											<xsl:for-each select="ns0:languageScript">
												<languageScript>
													<xsl:value-of select="string(.)"/>
												</languageScript>
											</xsl:for-each>
											<xsl:for-each select="ns0:sizePerLanguage">
												<sizePerLanguage>
													<size>
														<xsl:value-of select="string(ns0:size)"/>
													</size>
													<sizeUnit>
														<xsl:value-of select="string(ns0:sizeUnit)"/>
													</sizeUnit>
												</sizePerLanguage>
											</xsl:for-each>
										</languageInfo>
									</xsl:for-each>
									<modalityInfo>
										<xsl:for-each select="ns0:LingualityInfo/ns0:modalityType">
											<modalityType>
												<xsl:value-of select="string(.)"/>
											</modalityType>
										</xsl:for-each>
									</modalityInfo>
									<xsl:for-each select="ns0:SizeInfo">
										<sizeInfo>
											<size>
												<xsl:value-of select="string(ns0:size)"/>
											</size>
											<sizeUnit>
												<xsl:value-of select="string(ns0:sizeUnit)"/>
											</sizeUnit>
										</sizeInfo>
									</xsl:for-each>
									<xsl:for-each select="ns0:TextFormatInfo">
										<textFormatInfo>
											<xsl:for-each select="ns0:mime-type">
												<mimeType>
													<xsl:value-of select="string(.)"/>
												</mimeType>
											</xsl:for-each>
											<xsl:for-each select="ns0:sizePerTextFormat">
												<sizePerTextFormat>
													<size>
														<xsl:value-of select="string(ns0:size)"/>
													</size>
													<sizeUnit>
														<xsl:value-of select="string(ns0:sizeUnit)"/>
													</sizeUnit>
												</sizePerTextFormat>
											</xsl:for-each>
										</textFormatInfo>
									</xsl:for-each>
									<xsl:for-each select="ns0:CharacterEncodingInfo">
										<characterEncodingInfo>
											<xsl:for-each select="ns0:characterEncoding">
												<characterEncoding>
													<xsl:value-of select="string(.)"/>
												</characterEncoding>
											</xsl:for-each>
											<xsl:for-each select="ns0:sizePerCharacterEncoding">
												<sizePerCharacterEncoding>
													<size>
														<xsl:value-of select="string(ns0:size)"/>
													</size>
													<sizeUnit>
														<xsl:value-of select="string(ns0:sizeUnit)"/>
													</sizeUnit>
												</sizePerCharacterEncoding>
											</xsl:for-each>
										</characterEncodingInfo>
									</xsl:for-each>
									<xsl:for-each select="ns0:AnnotationInfo">
										<annotationInfo>
											<annotationType>
												<xsl:value-of select="string(ns0:annotationType)"/>
											</annotationType>
											<xsl:for-each select="ns0:annotationStandoff">
												<annotationStandoff>
													<xsl:value-of select="string((translate(string(.), '1falseru0 ', 't') = 't'))"/>
												</annotationStandoff>
											</xsl:for-each>
											<xsl:for-each select="ns0:segmentationLevel">
												<segmentationLevel>
													<xsl:value-of select="string(.)"/>
												</segmentationLevel>
											</xsl:for-each>
											<xsl:for-each select="ns0:annotationFormat">
												<annotationFormat>
													<xsl:value-of select="string(.)"/>
												</annotationFormat>
											</xsl:for-each>
											<xsl:for-each select="ns0:tagset">
												<tagset>
													<xsl:value-of select="string(.)"/>
												</tagset>
											</xsl:for-each>
											<xsl:for-each select="ns0:tagsetLanguageId">
												<tagsetLanguageId>
													<xsl:value-of select="string(.)"/>
												</tagsetLanguageId>
											</xsl:for-each>
											<xsl:for-each select="ns0:theoreticModel">
												<theoreticModel>
													<xsl:value-of select="string(.)"/>
												</theoreticModel>
											</xsl:for-each>
											<xsl:for-each select="ns0:annotationMode">
												<annotationMode>
													<xsl:value-of select="string(.)"/>
												</annotationMode>
											</xsl:for-each>
											<xsl:for-each select="ns0:annotationModeDetails">
												<annotationModeDetails>
													<xsl:value-of select="string(.)"/>
												</annotationModeDetails>
											</xsl:for-each>
											<xsl:for-each select="ns0:annotationTool">
												<annotationTool>
													<targetResourceNameURI>
														<xsl:value-of select="string(.)"/>
													</targetResourceNameURI>
												</annotationTool>
											</xsl:for-each>
											<xsl:for-each select="ns0:annotationStartDate">
												<annotationStartDate>
													<xsl:value-of select="string(.)"/>
												</annotationStartDate>
											</xsl:for-each>
											<xsl:for-each select="ns0:annotationEndDate">
												<annotationEndDate>
													<xsl:value-of select="string(.)"/>
												</annotationEndDate>
											</xsl:for-each>
											<xsl:for-each select="ns0:sizePerAnnotation">
												<sizePerAnnotation>
													<size>
														<xsl:value-of select="string(ns0:size)"/>
													</size>
													<sizeUnit>
														<xsl:value-of select="string(ns0:sizeUnit)"/>
													</sizeUnit>
												</sizePerAnnotation>
											</xsl:for-each>
											<xsl:for-each select="ns0:interannotatorAgreement">
												<interannotatorAgreement>
													<xsl:value-of select="string(.)"/>
												</interannotatorAgreement>
											</xsl:for-each>
											<xsl:for-each select="ns0:intraannotatorAgreement">
												<intraannotatorAgreement>
													<xsl:value-of select="string(.)"/>
												</intraannotatorAgreement>
											</xsl:for-each>
											<xsl:for-each select="ns0:annotator">
												<annotator>
													<personInfo>
														<xsl:for-each select="ns0:surname">
															<surname>
																<xsl:variable name="var39_lang">
																	<xsl:if test="@ns0:lang">
																		<xsl:value-of select="'1'"/>
																	</xsl:if>
																</xsl:variable>
																<xsl:if test="string(boolean(string($var39_lang))) != 'false'">
																	<xsl:attribute name="lang" namespace="">
																		<xsl:value-of select="string(@ns0:lang)"/>
																	</xsl:attribute>
																</xsl:if>
																<xsl:value-of select="string(.)"/>
															</surname>
														</xsl:for-each>
														<xsl:for-each select="ns0:givenName">
															<givenName>
																<xsl:variable name="var40_lang">
																	<xsl:if test="@ns0:lang">
																		<xsl:value-of select="'1'"/>
																	</xsl:if>
																</xsl:variable>
																<xsl:if test="string(boolean(string($var40_lang))) != 'false'">
																	<xsl:attribute name="lang" namespace="">
																		<xsl:value-of select="string(@ns0:lang)"/>
																	</xsl:attribute>
																</xsl:if>
																<xsl:value-of select="string(.)"/>
															</givenName>
														</xsl:for-each>
														<communicationInfo>
															<xsl:for-each select="ns0:CommunicationInfo/ns0:email">
																<email>
																	<xsl:value-of select="string(.)"/>
																</email>
															</xsl:for-each>
															<xsl:for-each select="ns0:CommunicationInfo/ns0:url">
																<url>
																	<xsl:value-of select="string(.)"/>
																</url>
															</xsl:for-each>
															<xsl:for-each select="ns0:CommunicationInfo/ns0:address">
																<address>
																	<xsl:value-of select="string(.)"/>
																</address>
															</xsl:for-each>
															<xsl:for-each select="ns0:CommunicationInfo/ns0:zipCode">
																<zipCode>
																	<xsl:value-of select="string(.)"/>
																</zipCode>
															</xsl:for-each>
															<xsl:for-each select="ns0:CommunicationInfo/ns0:city">
																<city>
																	<xsl:value-of select="string(.)"/>
																</city>
															</xsl:for-each>
															<xsl:for-each select="ns0:CommunicationInfo/ns0:country">
																<country>
																	<xsl:value-of select="string(.)"/>
																</country>
															</xsl:for-each>
															<xsl:for-each select="ns0:CommunicationInfo/ns0:telephoneNumber">
																<telephoneNumber>
																	<xsl:value-of select="string(.)"/>
																</telephoneNumber>
															</xsl:for-each>
															<xsl:for-each select="ns0:CommunicationInfo/ns0:faxNumber">
																<faxNumber>
																	<xsl:value-of select="string(.)"/>
																</faxNumber>
															</xsl:for-each>
														</communicationInfo>
														<xsl:for-each select="ns0:position">
															<position>
																<xsl:value-of select="string(.)"/>
															</position>
														</xsl:for-each>
														<xsl:for-each select="ns0:affiliation">
															<affiliation>
																<organizationName>
																	<xsl:variable name="var41_lang">
																		<xsl:if test="ns0:OrganizationInfo/ns0:organizationName/@ns0:lang">
																			<xsl:value-of select="'1'"/>
																		</xsl:if>
																	</xsl:variable>
																	<xsl:if test="string(boolean(string($var41_lang))) != 'false'">
																		<xsl:attribute name="lang" namespace="">
																			<xsl:value-of select="string(ns0:OrganizationInfo/ns0:organizationName/@ns0:lang)"/>
																		</xsl:attribute>
																	</xsl:if>
																	<xsl:value-of select="string(ns0:OrganizationInfo/ns0:organizationName)"/>
																</organizationName>
																<xsl:for-each select="ns0:OrganizationInfo/ns0:organizationShortName">
																	<organizationShortName>
																		<xsl:variable name="var42_lang">
																			<xsl:if test="@ns0:lang">
																				<xsl:value-of select="'1'"/>
																			</xsl:if>
																		</xsl:variable>
																		<xsl:if test="string(boolean(string($var42_lang))) != 'false'">
																			<xsl:attribute name="lang" namespace="">
																				<xsl:value-of select="string(@ns0:lang)"/>
																			</xsl:attribute>
																		</xsl:if>
																		<xsl:value-of select="string(.)"/>
																	</organizationShortName>
																</xsl:for-each>
																<xsl:for-each select="ns0:OrganizationInfo/ns0:departmentName">
																	<departmentName>
																		<xsl:variable name="var43_lang">
																			<xsl:if test="@ns0:lang">
																				<xsl:value-of select="'1'"/>
																			</xsl:if>
																		</xsl:variable>
																		<xsl:if test="string(boolean(string($var43_lang))) != 'false'">
																			<xsl:attribute name="lang" namespace="">
																				<xsl:value-of select="string(@ns0:lang)"/>
																			</xsl:attribute>
																		</xsl:if>
																		<xsl:value-of select="string(.)"/>
																	</departmentName>
																</xsl:for-each>
																<communicationInfo>
																	<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:email">
																		<email>
																			<xsl:value-of select="string(.)"/>
																		</email>
																	</xsl:for-each>
																	<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:url">
																		<url>
																			<xsl:value-of select="string(.)"/>
																		</url>
																	</xsl:for-each>
																	<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:address">
																		<address>
																			<xsl:value-of select="string(.)"/>
																		</address>
																	</xsl:for-each>
																	<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:zipCode">
																		<zipCode>
																			<xsl:value-of select="string(.)"/>
																		</zipCode>
																	</xsl:for-each>
																	<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:city">
																		<city>
																			<xsl:value-of select="string(.)"/>
																		</city>
																	</xsl:for-each>
																	<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:country">
																		<country>
																			<xsl:value-of select="string(.)"/>
																		</country>
																	</xsl:for-each>
																	<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:telephoneNumber">
																		<telephoneNumber>
																			<xsl:value-of select="string(.)"/>
																		</telephoneNumber>
																	</xsl:for-each>
																	<xsl:for-each select="ns0:OrganizationInfo/ns0:CommunicationInfo/ns0:faxNumber">
																		<faxNumber>
																			<xsl:value-of select="string(.)"/>
																		</faxNumber>
																	</xsl:for-each>
																</communicationInfo>
															</affiliation>
														</xsl:for-each>
													</personInfo>
												</annotator>
											</xsl:for-each>
										</annotationInfo>
									</xsl:for-each>
									<xsl:for-each select="ns0:DomainInfo">
										<domainInfo>
											<domain>
												<xsl:value-of select="string(ns0:domain)"/>
											</domain>
											<xsl:for-each select="ns0:sizePerDomain">
												<sizePerDomain>
													<size>
														<xsl:value-of select="string(ns0:size)"/>
													</size>
													<sizeUnit>
														<xsl:value-of select="string(ns0:sizeUnit)"/>
													</sizeUnit>
												</sizePerDomain>
											</xsl:for-each>
										</domainInfo>
									</xsl:for-each>
									<xsl:for-each select="ns0:TextClassificationInfo">
										<textClassificationInfo>
											<xsl:for-each select="ns0:textGenre">
												<textGenre>
													<xsl:value-of select="string(.)"/>
												</textGenre>
											</xsl:for-each>
											<xsl:for-each select="ns0:textType">
												<textType>
													<xsl:value-of select="string(.)"/>
												</textType>
											</xsl:for-each>
											<xsl:for-each select="ns0:register">
												<register>
													<xsl:value-of select="string(.)"/>
												</register>
											</xsl:for-each>
											<xsl:for-each select="ns0:subject_topic">
												<subject_topic>
													<xsl:value-of select="string(.)"/>
												</subject_topic>
											</xsl:for-each>
											<xsl:for-each select="ns0:conformanceToClassificationScheme">
												<conformanceToClassificationScheme>
													<xsl:value-of select="string(.)"/>
												</conformanceToClassificationScheme>
											</xsl:for-each>
											<xsl:for-each select="ns0:sizePerTextClassification">
												<sizePerTextClassification>
													<size>
														<xsl:value-of select="string(ns0:size)"/>
													</size>
													<sizeUnit>
														<xsl:value-of select="string(ns0:sizeUnit)"/>
													</sizeUnit>
												</sizePerTextClassification>
											</xsl:for-each>
										</textClassificationInfo>
									</xsl:for-each>
									<xsl:for-each select="ns0:TimeCoverageInfo">
										<timeCoverageInfo>
											<timeCoverage>
												<xsl:value-of select="string(ns0:timeCoverage)"/>
											</timeCoverage>
											<xsl:for-each select="ns0:sizePerTimeCoverage">
												<sizePerTimeCoverage>
													<size>
														<xsl:value-of select="string(ns0:size)"/>
													</size>
													<sizeUnit>
														<xsl:value-of select="string(ns0:sizeUnit)"/>
													</sizeUnit>
												</sizePerTimeCoverage>
											</xsl:for-each>
										</timeCoverageInfo>
									</xsl:for-each>
									<xsl:for-each select="ns0:GeographicCoverageInfo">
										<geographicCoverageInfo>
											<geographicCoverage>
												<xsl:value-of select="string(ns0:geographicCoverage)"/>
											</geographicCoverage>
											<xsl:for-each select="ns0:sizePerGeographicCoverage">
												<sizePerGeographicCoverage>
													<size>
														<xsl:value-of select="string(ns0:size)"/>
													</size>
													<sizeUnit>
														<xsl:value-of select="string(ns0:sizeUnit)"/>
													</sizeUnit>
												</sizePerGeographicCoverage>
											</xsl:for-each>
										</geographicCoverageInfo>
									</xsl:for-each>
								</corpusTextInfo>
							</xsl:for-each>
						</corpusMediaType>
					</corpusInfo>
				</resourceComponentType>
			</xsl:for-each>
		</resourceInfo>
	</xsl:template>
</xsl:stylesheet>
